MITLibraries/thing

Gemfile
Gemfile.lock
app/controllers/admin/advisors_controller.rb
app/controllers/admin/application_controller.rb
app/controllers/admin/degrees_controller.rb
app/controllers/admin/departments_controller.rb
app/controllers/admin/rights_controller.rb
app/controllers/admin/theses_controller.rb
app/controllers/admin/users_controller.rb
app/dashboards/advisor_dashboard.rb
app/dashboards/degree_dashboard.rb
app/dashboards/department_dashboard.rb
app/dashboards/right_dashboard.rb
app/dashboards/thesis_dashboard.rb
app/dashboards/user_dashboard.rb
config/routes.rb
test/fixtures/users.yml
test/integration/admin_dashboard_test.rb
test/test_helper.rb

**READY**
* adds admin dashboard via `administrate` gem
* only Users with `admin = true` can access the dashboards
* An admin ui at this early stage will let us confirm the data models
are indeed what we intend them to be and move more rapidly to staff
feedback (not yet though!).
* `administrate` seems flexible enough to use for semi-custom admin
interfaces without the hassle of weird DSLs.
* Most of what we will need for admin UI works out of the box. At this
time I believe adding the rest won't be awful. You can remind me when
I am wrong.
These are not intended to be complete admin interfaces. Instead, these are proposed
starting points for our admin interfaces.
Using credentials for MIT OpenID in your ENV (I know #9 is still open but for local dev you can use your own):
Confirm you …

Adds admin dashboards

---

Gemfile
Gemfile.lock
README.md
app.json
app/controllers/thesis_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/models/concerns/fake_auth_config.rb
app/models/user.rb
app/views/layouts/_site_header.html.erb
config/initializers/0_fake_auth_configuration.rb
config/initializers/devise.rb
test/models/fake_auth_test.rb

**READY**
We need to ensure that we don't accidentally enable fake auth in production. This checks on the Heroku app name as well as the `FAKE_AUTH_ENABLED` env variable.
- https://mitlibraries.atlassian.net/browse/TI-23
NO
YES (for some reason dotenv wasn't already there)

23 desuckify security

---

app/controllers/application_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb

**READY**
Moves skip verify_authenticity_token to appropriate controller rather than setting it globally. 
It is fairly complicated, but if you setup a shib IdP on testshib.org you can remove this changed line to see it block the authentication process. The skip is therefore necessary, but having it globally makes other form submissions insecure which was clearly not the intent.
- https://mitlibraries.atlassian.net/browse/TI-33
NO
NO

Moves skip verify_authenticity_token to appropriate controller

---

app.json

**READY**
Updates app.json for heroku PR builds to reflect what I think we'll need for PR builds to work as expected. Until we get some PR builds based on this (i.e. after this is merged and then open a new PR) it is difficult to be sure what is required so we may need some tweaks post merge.
- Sets fake_auth for PR builds
- adds ROLLBAR settings
- removes papertrail (I find it is not worth it for PR builds as you
get an email later on when the logs expire)
- removes skylight as it is unlikely to be helpful on pr builds
- removes private_key ~~and secret_key_base~~ that shouldn’t move to pr
builds from staging
- https://mitlibraries.atlassian.net/browse/TI-32
NO
NO

app.json updates

---

config/routes.rb
test/integration/authentication_test.rb
test/integration/routes_test.rb

**READY**
Root path is a splash page to anonymous users (pending TI-25), thesis submission page for logged-in users.
Fire up the app. Lo, it is the splash page. Log in. Lo, it is now the thesis submission form.
This was originally intended as just TI-24, but adding the test for redirect-after-login behavior turned out to be logically entailed by that work, so this will also close TI-26.
- https://mitlibraries.atlassian.net/browse/TI-26
- https://mitlibraries.atlassian.net/browse/TI-24
NO
NO

Front page is splash for anon users, thesis submission for logged-in

---

app/assets/javascripts/application.js
app/assets/javascripts/mark_downloaded.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/thing.scss
app/controllers/thesis_controller.rb
app/dashboards/thesis_dashboard.rb
app/models/ability.rb
app/models/thesis.rb
app/views/thesis/process_theses.html.erb
config/routes.rb
db/migrate/20180124144953_add_status_to_theses.rb
db/schema.rb
test/controllers/thesis_controller_test.rb
test/fixtures/theses.yml
test/models/thesis_test.rb

**READY**
Adds processing statuses to theses.  Indicates processing status on submissions queue page. Lets users mark theses as downloaded.
Go to `/process` on the PR build. There are 'mark downloaded' buttons on active theses (but only on active theses). Click them. Fun!
- https://mitlibraries.atlassian.net/browse/TI-37
YES
NO

37 thesis statuses

---

app/controllers/admin/application_controller.rb
app/dashboards/department_dashboard.rb
app/dashboards/thesis_dashboard.rb
app/models/ability.rb
app/models/user.rb
db/migrate/20180125202718_add_role_to_users.rb
db/schema.rb
test/controllers/thesis_controller_test.rb
test/fixtures/users.yml
test/integration/admin_dashboard_test.rb
test/models/user_test.rb

**READY**
This is pending review/merge of #41 - I want to make sure there isn't a conflict between the database migrations.
Adds roles (processor, thesis administrator, sysadmin) per stakeholder discussion. 
Library staff who are processing the thesis queue should be able to download theses and mark them as downloaded, but not to access the admin panel. Thesis administrators should be able to edit theses (including marking them as withdrawn) but not delete them.
Honestly I'm not sure how to do that - in theory you can create different accounts with fakeauth and assign them different roles and log in and see what happens, but in practice I can't log in with the same fakeauth account more than once (because it tries to create the user and fails due to nonuniqueness). I guess if you fix the …

41 additional roles

---

app/controllers/thesis_controller.rb
app/views/thesis/process_theses.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb

**READY**
Adds filter-by-status options to the thesis processing queue; tests them.
Go to `/process` on the PR build. Observe the view-by buttons. Click them.
- https://mitlibraries.atlassian.net/browse/TI-38
NO
NO

Let users filter thesis processing page by status

---

app/dashboards/user_dashboard.rb
test/integration/admin_dashboard_test.rb

**READY**
Allows user roles to be set through the admin dashboard.
This is permissible to all thesis admins, since the prior description of thesis admins is that they should be able to use the admin dashboards. However, I wonder if it would be appropriate to restrict this to sysadmins only? You're the one who's had the direct stakeholder conversations - tell me what you think.
Go to /admin on PR build, look at a user, yay there is a dropdown for editing their roles
- https://mitlibraries.atlassian.net/browse/TI-46
NO
NO

46 set user roles

---

Gemfile
Gemfile.lock
test/test_helper.rb

**READY**
There seems to be an ongoing debate between the reporters, rails and
minitest to determine who is at fault for things being messed up. I’m
just removing reporters for now and using the default reporter. We can
revisit this in the future if anyone really cares.
NO
YES (sort of... just a removal of one but you do need to bundle)

Remove minitest reporters

---

app.json
app/models/concerns/fake_auth_config.rb
db/seeds.rb

**READY**
1) Allow rake tasks to run without loading ENV 
Because of our fake auth detection in the Devise initializer, it was
not possible to run things such as `rake db:migrate` without prefixing
with `heroku local:run` which would load the ENV. This fixes that by
assuming fake auth in development unless it is explicitly set to false.
https://mitlibraries.atlassian.net/browse/TI-44
2) Seeds DB only in PR builds
Staging and Production will not run this automatically but PR builds
should.
https://mitlibraries.atlassian.net/browse/TI-45
https://devcenter.heroku.com/articles/github-integration-review-apps#the
-postdeploy-script
- On heroku PR build... sign in and marvel at the populated degrees, departments and rights.
- locally, run `bin/rails db:seed` without the `heroku local:run` prefix …

Seeds prs and rake without env

---

app/helpers/thesis_helper.rb
app/views/thesis/process_theses.html.erb
test/helpers/test_helper.rb

**READY**
(title says it all)
Look at `/process` or `/process?status=whatever` on the PR build. Sometimes a button is blue! It is the right button.
- https://mitlibraries.atlassian.net/browse/TI-50
NO
NO

Highlight currently active button on processing queue page

---

test/test_helper.rb

**READY**
Deletes files that were uploaded in integration tests.
Locally, check railsroot/tmp/storage before running tests. If you have run tests on a previous branch after we implemented file upload testing you should see a bunch of files.
After running this branch, you should not see anything there. Yay.
- https://mitlibraries.atlassian.net/browse/TI-54
NO
NO

Remove files uploaded in integration tests

---

app/views/thesis/process_theses.html.erb

**READY**
`file.service_url` expires; we should use a nonexpiring link to thesis content. I'm pretty sure this is the Rails-approved, All We Need To Do thing.
Compare file URL structures on staging and the PR build - they look different.
Save a staging build and PR build URL for >5 minutes and then go back to them - PR build one should still work, staging will have expired.
- https://mitlibraries.atlassian.net/browse/TI-55
NO
NO

Use permalinks, not expiring service URLs

---

app/dashboards/thesis_dashboard.rb
app/fields/file_field.rb
app/views/admin/application/_navigation.html.erb
app/views/fields/file_field/_show.html.erb
config/routes.rb
test/integration/admin_dashboard_test.rb

**READY**
- adds link to process theses in admin navigation
- adds link to download files from admin thesis show pages
- in the admin interface, the top link in the navigation should always be to the processing page
- in the admin thesis view page, links to download files should now exist if the thesis has files attached
- https://mitlibraries.atlassian.net/browse/TI-63
- and another one but Jira is down so I am not sure the number
NO
NO

add link to processing from admin and file downloads from show

---

app/models/thesis.rb
test/models/thesis_test.rb

**READY**
(see PR title)
Add a new thesis with a graduation year that is more than 5 years away from the current year (but still a 4-digit number after 1860). It should work on the PR build but not on staging.
Note that this introduces technical debt in that we will stop being able to add theses via the thesis ingest system starting in 7982 years.
- https://mitlibraries.atlassian.net/browse/TI-84
NO
NO

Remove all but the most trivial validation on graduation_year

---

app/models/thesis.rb
app/views/thesis/new.html.erb
test/controllers/thesis_controller_test.rb
test/fixtures/receipt_mailer/receipt_email
test/fixtures/theses.yml
test/integration/admin_dashboard_test.rb
test/models/thesis_test.rb

This requires changing a lot of files because the test fixtures
had different months and therefore this validity check caused
numerous tests to fail, but it isn't actually a very big change.
**READY**
On submission form on PR build, you will see that only February, June, and September are available in the graduation month drop-down. If you try to create a thesis with a different graduation month (e.g. in the shell), it will fail.
- https://mitlibraries.atlassian.net/browse/TI-85
NO
NO

Restrict valid months to February, June, September

---

app/models/concerns/fake_auth_config.rb
test/models/fake_auth_test.rb

**READY**
The PR builds now have incremented over 99 which seems to have
triggered a pattern match problem as they removed an extra character
from the middle of the expected URL to allow for the extra character
in the number to fit in their url size.
This should keep us safe for another 900 builds or so.
NO
NO

Updates pr build pattern match to allow fake auth

---

app/controllers/thesis_controller.rb
test/controllers/thesis_controller_test.rb
test/integration/thesis_test.rb

**READY**
There are two commits. The first adds a test for the _before_ behavior that was never tested in an Integration test.
The second, updates the behavior to reflect the change made in the UI which removed the multi select options for dept/degree. The controller was still expecting an array of values for those UI elements and thus was broken. The commit changes the controller expectation to be single values for each and updates tests in a couple locations to match that new behavior. The change to the UI that caused this bug landed last week. Ooops (on me).
NO
NO

Bugfix dept degree

---

README.md
app/controllers/application_controller.rb
config/routes.rb
test/integration/redirect_domains_test.rb

**READY**
Redirects from heroku or old domains to preferred domain if one is configured.
This is not yet ready for review, I wanted to see it on heroku before writing tests.
The PR build is configured to have a `PREFERRED_DOMAIN` of `yolo.mitlib.net`. You can see the various aspects of this working by:
- accessing the PR build by it's heroku name and being redirect to https://yolo.mitlib.net
- accessing https://yolo.mitlib.net/vireo/start and being redirected to root
- accessing https://yolo.mitlib.net/vireo/admin and being redirected to root
- https://mitlibraries.atlassian.net/browse/TI-91
NO
NO

Redirect if request host doesn't match configured preferred host

---

app/assets/javascripts/direct_uploads.js

**READY**
This is a workaround for some odd behavior where Firefox doesn't submit the form properly if you enter an error state, fix it, then submit again.
- https://mitlibraries.atlassian.net/browse/TI-92
NO
NO

Trigger submit after successful upload

---

app/views/thesis/new.html.erb

**READY**
Updated display order of departments to be alphabetical. Stakeholders confirmed Degrees do not need the same ordering for some reason. (I suspect we'll need a way to more explicitly control ordering for that at some point as it appears random but they like it so it's clearly not).
In the PR build, add some additional departments in a non-alpha order. They should be alpha on the ingest form dropdown select.
- https://mitlibraries.atlassian.net/browse/TI-96
NO
NO

Orders departments alphabetically on ingest form

---

README.md
config/environments/development.rb
config/environments/production.rb

**READY**
sane defaults but override-able without changing code if we need to go
to debug in prod for some reason
in prod, this change will not show debug events. In the PR build, if you add `LOG_LEVEL=debug` to the ENV config, it will show debug events.
- https://mitlibraries.atlassian.net/browse/TI-106
NO
NO

ENV configurable log levels

---

app/helpers/link_helper.rb

**READY/**
Updates accessibility of navigation to use `aria-current=page` instead of hidden spans.
Inspect the nav links in the PR build.
https://mitlibraries.atlassian.net/browse/TI-113
https://github.mit.edu/Accessibility-FY2018/thesis-submission/issues/1
NO
NO

Updates nav to use aria-current

---

app/models/ability.rb
test/controllers/thesis_controller_test.rb

**READY**
Allows `thesis_admin` and `processor` roles to view all Thesis records.
This bug has been around a while, but was only noticeable to staff that are thesis_admins or processors but also _not_ general admins.
The presence of effectively two roles systems (the named roles and the "admin" role) is technical debt and a new ticket will be opened to address that. The new ticket is https://mitlibraries.atlassian.net/browse/TI-115, the original is https://mitlibraries.atlassian.net/browse/TI-110
- https://mitlibraries.atlassian.net/browse/TI-110
NO
NO

Allow processors to view all Theses

---

app/controllers/thesis_controller.rb

**READY**
When working from the theses process list, marking a thesis complete, withdrawn or adding a note returned the processor to the process_path. However, that didn't take into account any filters or sorting they had done.
By using the redirect_back with a fallback to the process_path we should safely be able to return them to the same filtered list they started from while returning to the unfiltered list if the request doesn't have that information for some reason.
- https://mitlibraries.atlassian.net/browse/TI-116
NO
NO

Redirect back to filtered path when updating records

---

app/models/thesis.rb
test/models/thesis_test.rb

READY
Adds May to the `VALID_MONTHS` array of possible graduation months.
Beginning in 2020, commencement activities will begin one week earlier. This will place graduation day on May 29, 2020. However, some future graduation days will be in June (e.g., 2023).
Begin a test ingest in the CI deploy associated with this PR. The 'Month' drop-down menu should include the options February, May, June, September.
- https://mitlibraries.atlassian.net/browse/TI-130
NO
NO

Include May as a valid graduation month

---

README.md
app/controllers/admin/application_controller.rb
app/models/ability.rb
app/models/user.rb
test/fixtures/users.yml

**READY**
Removes remnants of sysadmin role, originally added here: https://github.com/MITLibraries/thing/pull/42
Also clarifies that the `Admin` flag is not a distinct role, but an additional level of permissions that can be added to any role.
The sysadmin role was deemed redundant and removed here: https://github.com/MITLibraries/thing/pull/267
We don't use it, but it's mentioned in a couple places. This PR removes those mentions.
Confirm that the sysadmin role no longer exists in the admin UI.
- https://mitlibraries.atlassian.net/browse/TI-115
- https://mitlibraries.atlassian.net/browse/TI-125
NO
NO

Fully remove sysadmin role and clarify Admin flag

---

Gemfile
Gemfile.lock
app/views/static/index.html.erb

**READY**
Updates the front page wording to reflect May 2020 theses workflow changes.
Removes `therubyracer` gem which is no longer needed.
View the main index page in the PR. It's all wording changes (other than removing therubyracer which can be tested by "is this PR build working at all".
- https://mitlibraries.atlassian.net/browse/TI-131
NO
YES (removes therubyracer)

Ti 131 update landing page

---

app/views/receipt_mailer/receipt_email.html.erb
app/views/static/index.html.erb
app/views/thesis/new.html.erb
test/fixtures/receipt_mailer/receipt_email

**READY**
This updates references to the May 2020 term to now include September
2020, as the processes we started in the spring are carrying forward to the
fall.
This is not a simple find/replace operation, however, as some references to
"May 2020" in context are to the starting point for these processes (which
is still the same) and others are to the terms covered by these processes
(which is now a list of two terms, rather than one).
The best way is probably to use the review application. Some of the
wording updates make the most sense in the context of the workflow.
- https://mitlibraries.atlassian.net/browse/ENGX-43
*Note:* I deleted the Documentation Todo because I don't think it is
relevant here?
NO
NO

Updates applicable terms to include September 2020

---

app/models/department.rb
app/models/transfer.rb
app/models/user.rb
db/migrate/20201203120000_create_transfers.rb
db/schema.rb
test/fixtures/transfers.yml
test/models/department_test.rb
test/models/transfer_test.rb
test/models/user_test.rb

This builds out the Transfer model as provided by Helen in ETS-62. It includes tests cribbed from the Thesis model, with the addition of some tests specific to attached files.
This is the first of several tickets that will define the bulk transfer capability.
The easiest way to see this change will be via the tests, or using a local console to create/update Transfers. The UI is unaffected.
https://mitlibraries.atlassian.net/browse/ETS-41
YES
NO

Adds Transfer model and relevant tests

---

app/models/department.rb
app/models/submitter.rb
app/models/user.rb
db/migrate/20201209213534_create_submitters.rb
db/schema.rb
test/fixtures/departments.yml
test/fixtures/submitters.yml
test/models/department_test.rb
test/models/user_test.rb

We need a Submitter model to know which Users can submit Transfers
for various Departments.
* https://mitlibraries.atlassian.net/browse/ETS-71
Adds Submitter model to join Transfers and Departments.
New database migration.
NO

ETS-71 Add submitter model

---

app/controllers/admin/transfers_controller.rb
app/controllers/transfer_controller.rb
app/dashboards/transfer_dashboard.rb
app/helpers/transfer_helper.rb
app/models/ability.rb
app/views/transfer/new.html.erb
app/views/transfer/show.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb
test/controllers/transfer_controller_test.rb
test/fixtures/submitters.yml
test/fixtures/transfers.yml
test/fixtures/users.yml
test/models/user_test.rb

The Ability model needs a submitter role to control who has
permission to deposit and manage transfers.
https://mitlibraries.atlassian.net/browse/ETS-40
This adds the transfer submitter role, along with the preliminary
TransferController with create and show methods. (Additional logic
will be added to the controller as needed.)
The Ability model now includes the following additional permissions:
* thesis_admin can create transfers and view any transfer
* transfer_submitter can create transfers and view their own transfers
* processor can view any transfer
* Generated the transfer dashboard and created a couple of stubbed
transfer views.
* Minor changes to our test fixtures to make the controller tests
clearer.
* Updated a thesis controller test assertion to redirect to the
login URL …

ETS-40 Add transfer submitter role

---

app/models/submitter.rb
app/models/transfer.rb
db/migrate/20201216104412_add_note_to_transfers.rb
db/schema.rb
test/fixtures/submitters.yml
test/fixtures/transfers.yml
test/models/transfer_test.rb

* The latest data model calls for a note field to be available - but not
required - for Transfer records.
* https://mitlibraries.atlassian.net/browse/ETS-78
* This adds a note field to the Transfer model, and updates one of the
fixtures to contain a long (over 255 characters) note. It also
includes relevant tests to make sure that a Transfer is considered
valid without one.
* The models have also been annotated using `bundle exec annotate
--models`
* Generating the annotations has added them for the Submitter model,
which previously did not have any.
YES
NO

Adds a note field to the Transfer model

---

config/initializers/devise.rb

**Why are these changes being introduced:**
* IST recently changed the IdP metadata to include multiple signing
certs for the main IdP. SAML exposes single and multiple certs via
distinct metadata elements rather than just providing single certs as
an array of 1.
**Relevant ticket(s):**
* https://mitlibraries.atlassian.net/browse/ETS-79
* This looks for either single or multiple certs and passes it all to
our SP
* Also updates the signing algorithm to RSA_256
**Testing suggestions:** 
The best way to test this is to deploy `main` to heroku staging with the settings for IdP metadata matching our official docs ( https://touchstone.mit.edu/metadata/MIT-metadata.xml ) and separately with the slim version ( …

SAML config now supports multiple signing cert

---

app/models/hold.rb
app/models/hold_source.rb
app/models/thesis.rb
db/migrate/20210111000000_create_holds.rb
db/schema.rb
db/seeds.rb
test/fixtures/hold_sources.yml
test/fixtures/holds.yml
test/fixtures/theses.yml
test/helpers/thesis_helper_test.rb
test/models/hold_source_test.rb
test/models/hold_test.rb
test/models/thesis_test.rb

This adds models for Holds and Hold_Sources, along with basic tests.
The details of these models are derived from the 1.2 data model that can be found linked to the Jira ticket in this PR.
YES
NO

Adds models for holds and hold_sources

---

app/dashboards/transfer_dashboard.rb
app/fields/attachment_field.rb
app/views/fields/attachment_field/_index.html.erb
app/views/fields/attachment_field/_show.html.erb
test/integration/admin_dashboard_test.rb

* The UI generated by the administrate gem for viewing transfers is broken
due to missing templates for file attachments and blobs.
* The gem doesn't support ActiveStorage, so we need to define custom
fields as described here: https://github.com/thoughtbot/administrate/blob/master/docs/adding_custom_field_types.md
* https://mitlibraries.atlassian.net/browse/ETS-88
* https://mitlibraries.atlassian.net/browse/ETS-65
* Defines custom fields for attachments.
* Removes blob as an attribute in all transfer templates to reduce
redundancy.
* Removes attachments and blobs as form attributes, since that doesn't
appear to work anyway.
* Changes grad date format in show page to %Y %B.
* Renders grad date and transfer date in index page.
I chose not to define a custom field for blobs, as I couldn't …

ETS-88 Fix generated dashboard UI for viewing transfers

---

app/controllers/thesis_controller.rb
app/dashboards/thesis_dashboard.rb
app/models/thesis.rb
app/views/thesis/_thesis.html.erb
db/migrate/20210120154818_make_thesis_title_and_abstract_nullable.rb
db/migrate/20210120161953_add_new_fields_to_thesis.rb
db/migrate/20210120213811_rename_thesis_note_to_processor_note.rb
db/schema.rb
test/controllers/thesis_controller_test.rb
test/fixtures/theses.yml
test/integration/thesis_test.rb
test/models/thesis_test.rb

The thesis model needs to incorporate changes in v1.2 of the data model. Closes ETS-90 and ETS-104.
* https://mitlibraries.atlassian.net/browse/ETS-90
* https://mitlibraries.atlassian.net/browse/ETS-104
* Makes title and abstract columns nullable.
* Adds author_note, files_complete, metadata_complete, and
publication_status columns.
* Renames note column to processor_note.
* Adds the above fields to the thesis admin dashboard show and form views.
* Changes instances of 'note' in views to 'processor note'.
* We will need to figure out where (outside of the admin dashboard) we
want these fields to render, and which users should be able to edit them.
* We will need to update …

Update thesis model and corresponding views

---

app/controllers/admin/advisors_controller.rb
app/dashboards/advisor_dashboard.rb
app/dashboards/thesis_dashboard.rb
app/models/advisor.rb
app/models/advisor_thesis.rb
app/models/thesis.rb
config/routes.rb
db/migrate/20210125212125_create_advisors_again.rb
db/schema.rb
test/fixtures/advisors.yml
test/fixtures/theses.yml
test/integration/admin_dashboard_test.rb
test/models/thesis_test.rb

This adds the Advisor model called for in the latest data model - via a two-way link table to Thesis records. There is also a new admin dashboard for this model.
There is not currently a dashboard for the actual Advisor_Thesis link table. If that is specifically needed as well, I can add it. The relationship can be managed via either Thesis or Advisor records (and I've added tests to confirm this behavior).
https://mitlibraries.atlassian.net/browse/ETS-95
YES
NO

Adds Advisor model, dashboard, and tests

---

app/dashboards/thesis_dashboard.rb
app/fields/file_field.rb
app/models/active_storage_attachment_extension.rb
app/views/fields/attachment_field/_show.html.erb
app/views/fields/file_field/_show.html.erb
app/views/thesis/_thesis.html.erb
config/initializers/active_storage_attachment_extension.rb
db/migrate/20210125145505_extend_active_storage_for_thesis_types.rb
db/schema.rb
test/integration/files_test.rb

* Our workflows require the ability to track the reason a file is being
submitted (primary thesis file, supplementary files, signature page,
etc)
* https://mitlibraries.atlassian.net/browse/ETD-30
* https://mitlibraries.atlassian.net/browse/ETD-145
* By extending the active_storage_attachment class and adding two fields
to the associated database table, we can easily provide the info our
app needs
* The extra module we load into the class is only necessary to allow an
enum, but it has a nice side effect of allowing us to include the
module with our models to be more visible to developers that there is
something non-default in our active_storage_attachment class.
By extending the active_storage_attachment class, it is possible future
changes to ActiveStorage may be in conflict with our …

Adds fields to active_storage_attachment

---

.github/workflows/ci.yml
app/controllers/admin/authors_controller.rb
app/controllers/thesis_controller.rb
app/dashboards/author_dashboard.rb
app/dashboards/thesis_dashboard.rb
app/mailers/receipt_mailer.rb
app/models/ability.rb
app/models/author.rb
app/models/thesis.rb
app/models/user.rb
app/views/thesis/_thesis.html.erb
app/views/thesis/process_theses.html.erb
app/views/thesis/show.html.erb
config/routes.rb
db/migrate/20210127184534_create_authors.rb
db/migrate/20210127192429_remove_user_id_from_thesis.rb
db/schema.rb
test/controllers/thesis_controller_test.rb
test/fixtures/authors.yml
test/fixtures/theses.yml
test/integration/admin_dashboard_test.rb
test/models/author_test.rb
test/models/thesis_test.rb
test/models/user_test.rb

* The user-thesis relationship should clarify which users authored a
thesis
* We need a place to record whether a thesis author has graduated
https://mitlibraries.atlassian.net/browse/ETD-75
* Adds Author table to join User and Thesis
* Adds graduation_confirmed boolean column to Author
* Adds basic administrate UI to edit graduation_confirmed field
This is a significant change. It initially broke the thesis processing
XHRs, the Ability model, the receipt mailer, and multiple admin UIs,
among other things. I believe I've fixed everything, but it's worth
noting that there may be additional fallout that we might not find until
later.
issues (link …

Add Author relationship model to application

---

test/integration/admin_dashboard_test.rb

One of our integration tests is failing in GitHub Actions (but not
locally), which is breaking all of our builds.
https://mitlibraries.atlassian.net/browse/ETD-173
This skips the problem test.
The ability to edit department_thesis through the admin dashboard will
not be tested until we fix the root cause.
NO
NO

Skip test that is failing in GitHub Actions

---

app/models/concerns/fake_auth_config.rb
test/models/fake_auth_test.rb

* For our review applications we enable some faked authentication for
easier testing. To prevent enabling this inadvertently on other tiers,
we restrict its operation to a specific naming pattern. This pattern
will change when we relaunch the application in a new domain name,
so this pattern must be updated.
* https://mitlibraries.atlassian.net/browse/ETD-148
* Updates the naming convention in the fake_auth concern
* Removes an unneeded test now that PR builds only follow one naming
convention
* Updates the name of the staging and production apps, which prevents
fake_auth from being enabled for those applications.
* This change *replaces* the naming pattern approved for review apps, so merging this branch will prevent `main` from being able to deploy to the old pipeline. I believe that …

Updates naming convention used around fake auth

---

app/models/thesis.rb
app/models/user.rb
test/models/thesis_test.rb
test/models/user_test.rb

The data model is set up in such a way that a Thesis with an associated
User cannot be destroyed. The desired behavior is that a Thesis can be
destroyed, and that will cascade to its associated Author entry without
destroying the User.
https://mitlibraries.atlassian.net/browse/ETD-182
* Adds dependent: :destroy option to the has_many: :authors association
in the Thesis model.
* Adds test coverage confirming desired behavior.
None.
NO
NO

ETD-182 Fix bug that prevents theses from being destroyed

---

app/models/thesis.rb
test/models/thesis_test.rb

When a user tries to delete a thesis with a hold in the admin UI,
the action fails due to the FK constraint. This is the behavior we want,
but we'd like to swallow the ActiveRecord::InvalidForeignKey error so
processors don't see a Rails error page.
To verify the changes, try deleting a thesis that has an associated hold in the admin UI. 
You should see a flash error like this: `Cannot delete record because dependent holds exist`.
Otherwise, if the thesis has no holds, it should delete successfully.
https://mitlibraries.atlassian.net/browse/ETD-153
This adds the :restrict_with_error option to the has_many: :holds
association on the Thesis model, which displays a friendly flash message
instead of the Rails error page.
None.
[our guide](https://mitlibraries.github.io/guides/basics/a11y.html) …

ETD-153 Add :restrict_with_error option to Thesis-Hold association

---

app/dashboards/hold_dashboard.rb
app/dashboards/hold_source_dashboard.rb

The current administrate field (DateTime) for created_at and updated_at
includes the timestamp, which adds visual clutter. This change was
requested as part of the UX review of the Hold UI.
* https://mitlibraries.atlassian.net/browse/ETD-175
* https://mitlibraries.atlassian.net/browse/ETD-106
* https://mitlibraries.atlassian.net/browse/ETD-170
This removes the timestamp from the DateTime fields in the Hold and
Hold Source UIs. The changes can be verified by confirming no timestamps
in the created_at and updated_at fields on the Hold show view and the Hold 
Source index and show views.
None.
issues (link to those issues in the Pull Request …

ETD-175 Update date format in Hold and Hold Source UIs

---

app/dashboards/hold_dashboard.rb
app/dashboards/hold_source_dashboard.rb
app/models/hold.rb
app/models/hold_source.rb
config/locales/en.yml
test/fixtures/holds.yml
test/fixtures/theses.yml
test/integration/admin_dashboard_test.rb
test/models/hold_source_test.rb
test/models/hold_test.rb

This is part of the work to implement recommendations made in the UX
review of the Hold and Hold Source UI. This changeset is detailed in
ETD-178, and originated in ETD-106 (see links in relevant tickets
section).
* https://mitlibraries.atlassian.net/browse/ETD-178
* https://mitlibraries.atlassian.net/browse/ETD-106
* https://mitlibraries.atlassian.net/browse/ETD-170
* Adds degrees field to Hold show view
* Adds degree date (thesis.grad_date) field to Hold show and index views
* Removes holds field from Hold Source create and edit views
* Removes source field from Hold Source show view
* Adds expired_holds field to Hold Source index view
It was requested that we remove the holds field from the Hold Source
create view, but administrate requires us to remove it from the edit
view as well. …

ETD-178 Update fields in Hold and Hold Source UIs

---

config/locales/en.yml

The UX review of the Hold and Hold Source UIs requested changes to UI
field labels.
* https://mitlibraries.atlassian.net/browse/ETD-174
* https://mitlibraries.atlassian.net/browse/ETD-106
* https://mitlibraries.atlassian.net/browse/ETD-170
* Adds i18n translations for the following fields:
* date_start
* date_end
* created_at
* updated_at
* case_number
* Adds a custom view for the Hold Source new form to make the title
singular
None.
NO
NO

ETD-174 Update field labels in Hold and Hold Source UIs

---

app/dashboards/hold_dashboard.rb
app/models/hold.rb
test/fixtures/authors.yml
test/models/hold_test.rb
test/models/thesis_test.rb

Author names are crucial for processors to clarify the correct
Thesis-Hold association, as they are more consistent than thesis titles.
* https://mitlibraries.atlassian.net/browse/ETD-107
* https://mitlibraries.atlassian.net/browse/ETD-177
* https://mitlibraries.atlassian.net/browse/ETD-106
* https://mitlibraries.atlassian.net/browse/ETD-170
* Adds an `author_names` convenience method to the Hold model that maps
all of the Author names associated with the corresponding Thesis.
* Adds `author_names` field to the Hold admin dashboard show and index
views.
None, but adding author info to the new and edit view will need to be
implemented separately (currently documented in ETD-177, linked above).
all issues introduced by …

ETD-107 Adds thesis author names to the Hold UI

---

app/controllers/registrar_controller.rb
app/models/ability.rb
app/models/registrar.rb
app/views/registrar/new.html.erb
app/views/registrar/show.html.erb
config/routes.rb
db/migrate/20210217183612_create_registrar.rb
db/schema.rb
test/controllers/registrar_controller_test.rb
test/fixtures/files/registrar.csv
test/fixtures/registrar.yml
test/models/registrar_test.rb

This creates a Registrar model to support uploading a CSV file that we'll get from the Registrar's office. There is an upload form, a (blank) show route, and test coverage to keep our current coverage level in place. I've confirmed that the uploaded file ends up in our s3 bucket.
Some notes on some specific choices I've made, in case any adjustments are needed:
* Both `admin` and `thesis_admin` roles have access to this form. I think I've written tests sufficient to clarify this, but I confess that at times the role system and admin flag trip me up.
* Jeremy commented on this already, but there is a user attribute on this model. I'm not sure if that's what's needed, but this may be a question for Helen.
* Do we need a MIME type check on the uploaded CSV file? The ticket mentions not doing …

Adds support for data uploads from Registrar

---

app/controllers/thesis_controller.rb
app/dashboards/thesis_dashboard.rb
app/models/thesis.rb
app/views/thesis/new.html.erb
db/migrate/20210225164332_add_coauthors_to_thesis.rb
db/schema.rb
test/fixtures/theses.yml
test/integration/thesis_test.rb
test/models/thesis_test.rb

* Part of the upcoming Registrar data import workflow will involve a
text string for each thesis containing the author's coauthors. The
import workflow will not attempt to reconcile multiple coauthors,
leaving that for manual work by a staff member. To enable that work,
we need to store this text string for later use.
* https://mitlibraries.atlassian.net/browse/ETD-192
* This adds a simple (nullable) string field to the Thesis model for
"coauthors". This field is also added to the Thesis Submission form,
the administrative dashboard (thesis display and thesis form).
* Relevant tests are added for this field as an optional element.
Not a side effect, but testing this branch has revealed an existing bug in the application, which has been recorded in Jira as …

Adds coauthors field to thesis model

---

app/dashboards/hold_dashboard.rb
app/models/hold.rb
test/integration/admin_dashboard_test.rb
test/models/hold_test.rb

Processors need certain information regarding a Hold's audit trail in the
admin UI:
* The date the hold was released
* The date the thesis file was received
* The user who created the hold
* https://mitlibraries.atlassian.net/browse/ETD-176
* Adds new fields to the Hold dashboard: created_by,
dates_thesis_files_received, date_released.
* Adds convenience methods to the Hold model to access the necessary
data.
We haven't yet implemented the primary flag for thesis files, so in this 
iteration, date_thesis_file_received becomes dates_thesis_files_received 
and lists the names and create dates of all associated files.
issues (link to those issues …

ETD-176 Add relevant audit trail fields to Holds UI

---

app/assets/stylesheets/administrate.scss
app/controllers/admin/holds_controller.rb
app/dashboards/author_dashboard.rb
app/dashboards/user_dashboard.rb
app/views/admin/holds/_form.html.erb
app/views/admin/theses/show.html.erb
app/views/layouts/admin/application.html.erb
config/initializers/assets.rb
test/integration/admin_dashboard_test.rb

When creating or editing a hold, processors need to be able to clearly
identify its parent record. The selectize drop-down displays the title,
but processors also need to be able to search by author name and kerb ID,
and the corresponding degree info must be visible.
* https://mitlibraries.atlassian.net/browse/ETD-177
* Adds a 'New hold' button to the Thesis show page that links to a new
Hold form prepopulated with information about the corresponding Thesis.
* Overrides the administrate HoldsController#new action to work with the
thesis_id param.
* Adds a search field to the Authors dashboard index page to search by 
display_name, kerberos_id, and uid.
* Adds kerberos_id to Users dashboard index page to provide another 
path to access the desired thesis.
* Adds a new stylesheet for the …

ETD-177 Add logic to create a Hold through Thesis

---

app/models/ability.rb

* We had a bug where Submitters were having their roles updated in the
database to `thesis_submitter` which was not the intent and would have
led to problems in the future.
* https://mitlibraries.atlassian.net/browse/ETD-193
* This fixes the bug where we set the User role to `thesis_submitter`
and saved it to the database by instead calling the method
that ensures they have the appropriate permissions.
NO
NO

Fixes implicit submitter role

---

app/assets/stylesheets/administrate.scss
app/dashboards/hold_dashboard.rb
app/models/hold.rb
app/views/admin/holds/_form.html.erb
config/locales/en.yml

This addresses UX feedback given in response to the recent Hold UI updates
(mocked up in ETD-106 and implemented across various other tickets).
* https://mitlibraries.atlassian.net/browse/ETD-189
* Adds an i18n translation to render processing_notes field as 'Hold
notes'.
* The display_resource method now returns "Hold for: #{thesis.title}" to
clarify that the current resource is a Hold.
* Renders dates_thesis_files_received in form as a read-only element.
* If a new Hold is created without a thesis ID param, the form won't
populate the dates_thesis_files_received field dynamically based on the
contents of the thesis field. This shouldn't be a problem, since the
workflow will be to create holds through theses.
* Adding dates_thesis_files_received to the form broke the 'new' action
if no …

ETD-189 Implement requested UX changes for Hold UI

---

app/assets/stylesheets/administrate.scss
app/controllers/admin/application_controller.rb
app/controllers/admin/submitters_controller.rb
app/dashboards/submitter_dashboard.rb
app/dashboards/user_dashboard.rb
app/fields/user_submitter_field.rb
app/models/ability.rb
app/views/admin/holds/_form.html.erb
app/views/fields/user_submitter_field/_show.html.erb
app/views/layouts/admin/application.html.erb
config/locales/en.yml
test/integration/admin_dashboard_test.rb
test/integration/admin_submitter_dashboard_test.rb

* It is difficult for our staff to quickly see which users are
authorized submitters for various departments
* Making it so looking up the user and being able to quickly see which
departments they can submit to will allow for initial setup and
ongoing maintainance more efficient
* https://mitlibraries.atlassian.net/browse/ETD-181
* adds Submitters to the User show dashboard
* creates a custom field to jumpstart create a new Submitter
The custom field is forked from the gem's `has_many` code. If there are
changes upstream, we'll need to move them locally to this forked copy.
all issues …

Update user dashboard to reflect submitters

---

app/controllers/hold_controller.rb
app/dashboards/hold_dashboard.rb
app/fields/hold_history_field.rb
app/helpers/hold_helper.rb
app/models/ability.rb
app/models/hold.rb
app/views/fields/hold_history_field/_show.html.erb
app/views/hold/show.html.erb
config/locales/en.yml
config/routes.rb
test/controllers/hold_controller_test.rb
test/integration/admin_dashboard_test.rb
test/integration/hold_test.rb

We need a way to see the full audit trail for a Hold record. Only some
paper_trail fields are currently visible in the Hold administrate UI.
* https://mitlibraries.atlassian.net/browse/ETD-186
* Adds a hold history page (the Hold show page) that displays audit
information for a given Hold record. Initially, I chose to display the
following fields for each version:
* The event type (e.g., create/update/destroy);
* The user who modified the record; and
* Everything in the version changeset.
* Adds a custom field, hold_history, to administrate, to provide a link
to the hold history page from the Hold dashboard.
* Adds Hold#show method to route to the hold history page.
* Added complexity: we now have a Hold controller with a show method, a
corresponding view and route, and a Hold helper.
* …

ETD-186 Create UI for full listing of hold history

---

db/migrate/20210317165853_update_dw_name_in_departments.rb
db/schema.rb
lib/tasks/db.rake

We have several hundred official degrees and departments with unique
codes and names from the Data Warehouse that need to be seeded to the
database. Ideally this process will be repeatable for initial testing
and future dev/test/staging database resets.
* Adds two db-namespaced rake tasks, one to seed the degrees and
another to seed the departments.
* https://mitlibraries.atlassian.net/browse/etd-169
YES
NO

Add rake tasks to seed degrees and departments

---

.github/PULL_REQUEST_TEMPLATE.md
app/controllers/application_controller.rb
app/views/layouts/_site_nav.html.erb
app/views/static/index.html.erb
test/integration/authentication_test.rb
test/integration/nav_test.rb

We need a landing page for the public UI to direct students and
transfer submitters to the correct form.
* https://mitlibraries.atlassian.net/browse/ETD-212
* https://mitlibraries.atlassian.net/browse/ETD-209 (mockup)
This modifies the existing static index page to reflect the new app's
purpose and functionality.
* Transfer submitters are now redirected after login to the transfer
submission form.
* Removes an extra newline from the PR template (completely unrelated,
but it was irking me).
NO
NO

ETD-212 Implement public UI home page

---

app/views/thesis/new.html.erb

This rolls back the aggregation that I tried to enact on the degree field of the new thesis form. While it had the desired effect locally with a SQLite database, the PG database on Heroku is throwing an error because the Degree ID field isn't involved in the aggregation:
The actual error encountered in the Heroku logs is:
```
ActionView::Template::Error (PG::GroupingError: ERROR:  column "degrees.id" must appear in the GROUP BY clause or be used in an aggregate function
```
NO
NO

Removes aggregation on degree field in new thesis form

---

app/jobs/registrar_import_job.rb
app/models/thesis.rb
test/jobs/registrar_import_job_test.rb

In preparing for registrar data import on production, a small bug was
identified where a blank coauthor field in the CSV caused an error
while updating an existing thesis.
* Updates the Thesis.create_or_update_from_csv method to convert a nil
value from the CSV coauthor field to a string, enabling the desired
logic
* Also updated the registrar_import_job result output to display any
errors encountered, just to make the final results clear in the logs
at the end of the job.
NA
issues (link to those issues in the Pull Request …

Fix minor coauthor bug in registrar import

---

app/assets/javascripts/student_thesis_form.js
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

This writes a small javascript function to read the state of the Copyright field, and set the state of the License field according to what it finds. This function is then called both during initial page load, and then also by a change() listener on the Copyright field.
This could probably have been either a Javascript object, or written in native javascript with no jQuery. I'm open to refactoring this if whomever reviews it would like.
Ticket: https://mitlibraries.atlassian.net/browse/ETD-236
NO
NO

Converts License field to conditionally display

---

app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

This implements two requested hotfixes:
- Adds asterisks to a few field labels (and label-like elements, like "Degree date" and "Thesis supervisor(s)". Also the Abstract field on the edit form, which was left off initially.
- Changes the label on the name field based on stakeholder feedback
Tickets:
- Abstract has no ticket
- Name change: https://mitlibraries.atlassian.net/browse/ETD-237
NO
NO

Hotfixes: Adds missing asterisks, and name field label

---

README.md
app/controllers/thesis_controller.rb
app/mailers/receipt_mailer.rb
app/views/receipt_mailer/receipt_email.html.erb
test/fixtures/receipt_mailer/receipt_email
test/fixtures/users.yml
test/integration/admin/admin_thesis_test.rb
test/integration/thesis_test.rb
test/mailers/previews/receipt_mailer_preview.rb
test/mailers/receipt_mailer_test.rb

We want to send a helpful confirmation email to students when they
submit their thesis info.
* https://mitlibraries.atlassian.net/browse/ETD-200
This updates the ReceiptMailer to include the information specified in
in the contextual content doc. The mailer is called in the update action
of the Thesis controller.
* In my local environment, I wasn't sure how to  manually test this beyond
looking at the preview. We will want to try sending emails in the PR
build/staging to ensure that the mailer behaves as expected.
* Some weird spacing in the receipt_email fixture was required to pass
the assertion comparing the fixture to the email body.
issues …

ETD-200 Update student submission mailer for new application

---

app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

This converts text elements into readonly form elements, which should address the feedback we got from the web accessibility center.
(Ironically, this change is being flagged by accesslint - but I've checked these controls in both ANDI and WAVE, and neither flags this arrangement. I trust them more than accesslint if the two come into conflict.)
NO
NO

Convert uneditable information to read-only fields

---

app/controllers/application_controller.rb
test/controllers/hold_controller_test.rb
test/controllers/registrar_controller_test.rb
test/controllers/thesis_controller_test.rb
test/controllers/transfer_controller_test.rb
test/integration/thesis_test.rb

* there are states in the app where a user might click a link that they
are not authorized to access. Ideally, we'd not display that link.
For now, we are redirecting to root and displaying a message they are
not authorized rather than throwing an exception.
* https://mitlibraries.atlassian.net/browse/ETD-215
* We are now redirecint all authorization errors to root with a message
they are not authorized.
* The result is now a 200 instead of a 403. For this application that
seems fine as it will only occur for authenticated human users.
* Tests had to be updated to reflect it was no longer a 403.
- [x ] ANDI or Wave has been run in accordance to
[our …

User friendly authorization error

---

app/models/thesis.rb
app/views/thesis/new.html.erb
test/integration/thesis_test.rb
test/models/thesis_test.rb

The degree drop-down is difficult to use due to duplicate entries. The
degree will always be supplied by the registrar, so we don’t need it from
creation.
* https://mitlibraries.atlassian.net/browse/ETD-230
This removes the degree validation from the thesis model and removes the
degree field from the new form.
A confirmation email sent to a student that completes the new form will
show no degree associated with their thesis, which may be confusing.
NO
NO

ETD-230 Remove degree field from new thesis form

---

app/controllers/thesis_controller.rb
app/views/thesis/_advisor_fields.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

This addresses three of the items on the pre-launch punchlist: 1b (initial field), 1c (add another supervisor), and 1e (focus). The final item, 1d (handling blank fields) is still in progress - but we've decided to get the stablished fixes through code review now so that other work can proceed with less chance of a merge conflict.
NO
NO

WIP - Updates to thesis supervisor / advisor field behavior

---

app/views/thesis/new.html.erb

The degree year field in the thesis form is currently free text, but
the stakeholders would prefer that it be a drop-down with last year,
current year, and next year as the options.
* https://mitlibraries.atlassian.net/browse/ETD-250
* Changes the field in thesis/new to a select using simpleform's collection
option, which allows us to specify the values in an array.
* Uses the `last_year` and `next_year` methods on the `Date` object to
evaluate which years to add to the collection.
None.
NO
NO

ETD-250 Change degree year field to a select

---

app/views/static/index.html.erb
app/views/thesis/_sidebar.html.erb
app/views/thesis/_welcome.html.erb
app/views/thesis/confirm.html.erb

If a user has configured a browser-based email client as their default,
then mailto links will open in the same window. We want those links to
open in a new window. This is stakeholder feedback on ETD-251.
* https://mitlibraries.atlassian.net/browse/ETD-251
Adds target="_blank" to mailto links in the landing page and thesis
partials.
None.
NO
NO

Open mailto links in a new window/tab

---

app/assets/javascripts/student_thesis_form.js
app/assets/stylesheets/thing.scss
app/controllers/thesis_controller.rb
app/models/thesis.rb
app/views/thesis/_advisor_fields.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

This resolves the final aspect of ETD-240, enabling the user to remove thesis supervisor fields from the form under some conditions. This avoids the problem of a user having created too many fields, as well as allowing user to remove supervisors they have already identified.
At the same time, this change adds a check to the form logic to prevent the user from removing the _last_ supervisor field.
This is all possible because the supervisor fields are not backed by any authority, and all values are specific to each thesis. This work creates a side effect, however, of allowing orphan supervisors to accumulate - because when an existing supervisor is removed from a Thesis, the link is deleted but the supervisor record itself is kept. Eventually we will need a cleanup task, or to convert …

Allow removal of supervisor fields

---

app/views/thesis/_advisor_fields.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

Some thesis form fields already used aria-describedby, but not all of them. This extends the practice to all fields which have a visible hint. It also uses a slightly different invocation of the attribute, so existing fields are converted to the new style as well.
Additionally, the value for newly-created supervisor fields is dynamically overwritten using the `cocoon:after-insert` hook, which we'd previous used to set focus. Now, we also assign a unique value to each field for use by the aria-describedby attribute.
NO
NO

Extend use of aria-describedby attributes on thesis forms

---

app/controllers/registrar_controller.rb
app/views/layouts/_site_nav.html.erb
test/controllers/registrar_controller_test.rb
test/integration/nav_test.rb

This adds two new links to the main navigation, scoped to those who can perform those actions. The first is for uploading a CSV file from the registrar, the second is to initiate harvesting of that file.
Please note: I've added a bit of setup to the navigation test fixtures now, to make sure that the /registrar path works as expected. This is how we deal with attachments for the model tests, but I wonder if the right step here isn't to actually change how our fixtures are defined.
NO
NO

Adds harvest and registrar paths to navigation

---

app/helpers/thesis_helper.rb
test/helpers/thesis_helper_test.rb

* Some registrar loaded data does not have a title
* We need to display a list of theses to users if they have more than
one thesis
* The helper method to display "Untitled thesis" only handled empty
strings
* This change adds handling nils to that method as well.
* https://mitlibraries.atlassian.net/browse/ETD-273
* Returns our expected text for nil thesis titles
* Added regression tests in the helper for both empty, nil and populated
titles
(not …

Handle nil thesis titles in title_helper

---

app/assets/stylesheets/thing.scss
app/controllers/transfer_controller.rb
app/models/ability.rb
app/models/transfer.rb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
app/views/transfer/_welcome.html.erb
app/views/transfer/confirm.html.erb
app/views/transfer/new.html.erb
config/routes.rb
test/controllers/transfer_controller_test.rb

Update Transfer submission UI based on stakeholder feedback

---

app/dashboards/thesis_dashboard.rb
app/models/thesis.rb
test/models/thesis_test.rb

** Why are these changes being introduced:
* There is a bug in the thesis model which prevents updating thesis
records via the admin dashboard. We specify graduation dates in the UI
via separate month and year fields, but the information gets stored
internally as a unified date. There is a method to build this date,
but it only called on record creation - not when the record is updated
* Additionally, the admin dashboard currently imposes conflicting
requirements on the graduation_month field, being both a number and
the name of the month.
** Relevant ticket(s):
* https://mitlibraries.atlassian.net/browse/ETD-216
** How does this address that need:
* This updates the thesis model to call combine_gradaution_date every
time the record gets saved, not just for initial creation.
* This change …

Fix bugs around thesis graduation date

---

README.md
lib/tasks/debug.rake

* It is difficult to see what is in a production or staging SAML
response as they are encrypted
* It is often useful to see what is included in a production or staging
SAML response
* https://mitlibraries.atlassian.net/browse/ETD-275
* adds a rake task that will read SP key and cert from .env and then
decrypt and output the SAML response
- It remains a bit tedious to get the SAML response in a useful format.
NO …

Adds task to assist in examining SAML responses

---

app/controllers/transfer_controller.rb
app/mailers/receipt_mailer.rb
app/views/receipt_mailer/transfer_receipt_email.html.erb
test/integration/admin/admin_transfer_test.rb
test/integration/transfer_test.rb
test/mailers/receipt_mailer_test.rb

This implements the transfer success email, with associated tests.
NO
NO

Implement transfer receipt email

---

app/assets/javascripts/student_thesis_form.js
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

This fixes the issue where focus is left undefined when a supervisor field is removed.
It also fixes a separate-but-related bug where the "remove this supervisor" link is not appropriately removed on the edit form in some conditions.
Note: I'm not sure how to use ANDI or Wave when changes like this are made - but I _have_ tested this code under keyboard navigation and using visual cues under my locally-installed browsers (Firefox, Chrome, and Safari).
NO
NO

Maintain focus during removal of supervisor field

---

app/assets/javascripts/direct_uploads.js
app/assets/stylesheets/direct_uploads.scss
app/views/transfer/_welcome.html.erb
app/views/transfer/confirm.html.erb
app/views/transfer/new.html.erb

Ticket: https://mitlibraries.atlassian.net/browse/ETD-283
NO
NO

Address transfer submission process based on user feedback

---

app/views/shared/_you_are.html.erb

** Why are these changes being introduced:
* There is a double period in the rendering of the "You are logged in"
partial
** Relevant ticket(s):
* n/a
** How does this address that need:
* This removes the extra period.
** Document any side effects to this change:
* None
NO
NO

Removes extra period in "You are" partial

---

app/controllers/transfer_controller.rb
app/models/ability.rb
app/views/layouts/_site_nav.html.erb
app/views/transfer/_empty.html.erb
app/views/transfer/_transfer.html.erb
app/views/transfer/select.html.erb
app/views/transfer/show.html.erb
config/routes.rb
test/controllers/transfer_controller_test.rb
test/fixtures/transfers.yml
test/integration/nav_test.rb
test/models/transfer_test.rb

This implements the first few steps of the Transfer Processing workflow:
- Creates a page showing all transfer records, with links to each transfer detail page
- Implements a jQuery plugin (DataTables) to allow interactive filtering and sorting of the list of Transfers
NO
NO

First part of Transfer processing

---

app/assets/stylesheets/thing.scss
app/controllers/transfer_controller.rb
app/models/ability.rb
app/views/transfer/show.html.erb
config/routes.rb
test/controllers/transfer_controller_test.rb

This adds the first part of the transfer processing form. Along the way it also changes the ability model to restrict who can see this path, and it restructures the controller tests for Transfer records.
This work addresses two tickets:
https://mitlibraries.atlassian.net/browse/ETD-277
https://mitlibraries.atlassian.net/browse/ETD-278
**Special note:** I'm not thrilled by the approach taken by the last test in the controller test file, but I don't see an alternative other than re-doing the fixtures (which feels like work that's going to spiral). If that's needed, I'll do it - but I wanted to make that decision via code review.
issues (link to …

Work in progress toward Transfer processing form

---

app/dashboards/thesis_dashboard.rb
app/models/thesis.rb
db/migrate/20210511192431_add_dspace_handle_to_thesis.rb
db/schema.rb
test/fixtures/theses.yml
test/models/thesis_test.rb

When theses are published to DSpace, the SWORD submission will return a handle that we want to store in this system.
* Adds dspace_handle field to the thesis model with corresponding test
* Adds dspace_handle field to admin view of thesis info (note, does not add this field to the edit form, as it is not intended to be edited other than by the SWORD submission job)
* https://mitlibraries.atlassian.net/browse/ETD-296
YES
NO

Add DSpace handle to thesis model

---

app/assets/stylesheets/thing.scss
app/controllers/transfer_controller.rb
app/models/ability.rb
app/views/transfer/_empty_target.html.erb
app/views/transfer/_thesis_target.html.erb
app/views/transfer/show.html.erb
test/controllers/transfer_controller_test.rb

This completes building the transfer processing form UI, adding the table of relevant theses. Future work will complete the actual work requested by the form.
* https://mitlibraries.atlassian.net/browse/ETD-279
* https://mitlibraries.atlassian.net/browse/ETD-280
I'm curious if there is a better way to peform the filtering. In testing, it appears that thesis records which carry multiple departments are appearing in the filtered list, but when rendered these theses would only show the filtered department name. Reloading the record would restore both, but I'm somewhat concerned that the way the filtering is being done too aggressively (i.e. the record is being manipulated, and if saved we would lose some thesis-department links)
[our …

Add thesis field to transfer processing form

---

app/assets/stylesheets/thing.scss
app/controllers/transfer_controller.rb
app/models/transfer.rb
app/views/transfer/_transfer.html.erb
app/views/transfer/show.html.erb
test/controllers/transfer_controller_test.rb
test/models/transfer_test.rb

This makes the Transfer processing form actually do work, attaching selected files from a Transfer to the Thesis record identified by the user.
NO
NO

Assign selected files to identified Thesis

---

app/controllers/thesis_controller.rb
app/models/ability.rb
app/views/layouts/_site_nav.html.erb
app/views/thesis/_select_empty.html.erb
app/views/thesis/_select_thesis.html.erb
app/views/thesis/select.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb
test/fixtures/theses.yml
test/helpers/thesis_helper_test.rb
test/integration/nav_test.rb

This implements the thesis processing queue at /thesis/select, a parallel construct to the transfer processing queue that was introduced in the last sprint. The queue currently contains no links or action steps, which will be introduced in future tickets.
Ticket: https://mitlibraries.atlassian.net/browse/ETD-308
NO
NO

Create thesis processing queue

---

app/mailers/receipt_mailer.rb
app/views/receipt_mailer/transfer_receipt_email.html.erb
app/views/transfer/confirm.html.erb
app/views/transfer/show.html.erb

There are a few requested changes that have been identified via user testing of the transfer form and processing workflow. This PR attempts to address those items.
Tickets:
https://mitlibraries.atlassian.net/browse/ETD-339
https://mitlibraries.atlassian.net/browse/ETD-340
The first commit in this PR addresses the items in ETD-339, the second commit responds to ETD-340.
I've opted not to write a full blown PR message thus far, but can if that's desired.
NO
NO

Addresses punchlist items

---

app/dashboards/hold_dashboard.rb
test/integration/admin/admin_hold_test.rb

Certain fields in the Hold dashboard, which are generated via convenience
methods and not stored in the db,  were defined as Field::String. Because
Field::String is searchable by default, this caused the dashboard search
to break when it tried to query nonexistent columns.
https://mitlibraries.atlassian.net/browse/ETD-304
This changes the offending fields to Field::Text, which are not
searchable by default.
* When I fixed this bug, I noticed that the only searchable field was
status. I added thesis title as another searchable field, since there
aren't many Hold model fields that are searchable in administrate.
* Notably, status is searchable only if you add a colon to the
end of the querystring (e.g., 'active:'), due to some weirdness with
how collection filters work in administrate.
[our …

Bugfix for broken Hold dashboard searches

---

app/jobs/registrar_import_job.rb

A typo in the import job caused the job to crash when an expected error was logged. This fixes it.
* Fixes the typo
Note: because this is semi-urgent, this commit does not update tests to ensure that this particular rescue block is covered. I will add a Jira ticket for that to make sure the tests are updated ASAP.
NO
NO

Fix a typo in the import job

---

app/controllers/thesis_controller.rb
app/models/author.rb
app/models/hold.rb
app/models/thesis.rb
app/views/thesis/process_theses.html.erb
db/migrate/20210621143516_add_issues_found_to_thesis.rb
db/schema.rb
test/fixtures/authors.yml
test/fixtures/holds.yml
test/fixtures/theses.yml
test/integration/thesis_test.rb
test/models/thesis_test.rb

This adds the `issues_found` flag, as well as an `update_status` method that will be called via lifecycle hooks whenever a thesis, hold, or author record is saved. The update_status method also relies on two new inversion helper methods that allow for the five qualifying conditions to be checked via `[a,b,c,d,e].all?` logic.
There is a guard check in the method that returns early if the thesis has already been picked up by the publication workflow.
I've tried to write unit tests pretty thoroughly on this work, to make sure that changes are happening as we expect. Hopefully they are sufficient, so I welcome some pretty tight scrutiny on all of this.
* https://mitlibraries.atlassian.net/browse/ETD-343
all issues …

Implements publication status, adds issues_found flag

---

app/assets/stylesheets/thing.scss
app/views/thesis/select.html.erb

This repeats the filter buttons that we used on the transfer processing queue, building a row of filter buttons on the thesis queue that focus on publication_status.
Bonus: CodeClimate doesn't seem to complain about the duplicated javascript!
https://mitlibraries.atlassian.net/browse/ETD-345
NO
NO

Adds filter buttons for thesis publication status

---

app/models/hold.rb
app/views/hold/show.html.erb

Certain data associated with a hold (author names, degree information,
and dates thesis files received) are not included in the hold history
page because these fields are not part of the Hold model and are
therefore not under audit control.
* https://mitlibraries.atlassian.net/browse/ETD-341
This adds the current values of the fields mentioned to the top of the
hold history for users to reference while reviewing a hold's audit
trail.
I refactored a couple of conditionals into guard clauses in the Hold model.
NO
NO

ETD-341 Display additional data in hold history view

---

app/dashboards/hold_dashboard.rb
app/models/hold.rb
test/models/hold_test.rb

Author names were not searchable in the Hold dashboard because
administrate accesses them from a convenience method rather than the
User model, causing the the Active Record query to fail.
* https://mitlibraries.atlassian.net/browse/ETD-353
This adds an association to the User model on the Hold model, and a
corresponding 'users' attribute to the Hold dashboard, which is searchable
on display_name, uid, and kerberos_id. These are the same fields that are
currently searchable on the Author dashboard, but we can add more fields
if it proves useful.
None, aside from the new association. We are still using the author_names
convenience method to display the names in the UI, since the has_many
association renders in a not-so-useful way in administrate.
[our …

ETD-353 Make author names searchable on Hold dashboard

---

app/dashboards/transfer_dashboard.rb

This enables staff searching of records within the admin transfer panel.
* https://mitlibraries.atlassian.net/browse/ETD-334
One caveat is that this will make the graduation year searchable, but not the graduation month. Additionally, searching much match against one and only one field - so something like "SHASS Joe" will fail, even if both "SHASS" and "Joe" would each return an overlapping set of records.
Another caveat is that I haven't asked for stakeholder review of this change yet - without a robust set of records in a review app, I'm not sure how useful that would be. I'm thinking that we can take care of this after the code merges and it gets to the staging dataset.
all issues introduced by these changes have …

Adds searchable flag to certain transfer fields

---

app/dashboards/department_dashboard.rb
app/models/department.rb
config/locales/en.yml
db/migrate/20210629202931_add_authority_key_to_departments.rb
db/schema.rb
test/fixtures/departments.yml
test/models/department_test.rb

This adds the authority key field to the Department model, in support of future SWORD submissions to DSpace. Field labels are handled via the i18n locales file.
*Please note* the original ticket calls for this field to be editable by thesis processors. We have thus far used the "admin" flag to achieve this ability, so no work is needed on this front. I've done a bit of work to see how processors could be given access to this area without the flag, and - while it is possible - there's some weirdness in how this change would happen that makes me want to set it aside for now. I will set up a separate PR for how that change would happen, to allow us to consider the change de-coupled from the immediate timeline of this project.
* https://mitlibraries.atlassian.net/browse/ETD-347
[our …

Adds DSpace authority key field to department

---

app/views/thesis/process_theses.html.erb

This adds the `target="_blank"` attribute to a specific link on the thesis processing form. This step is being done in response to staff user requests after testing.
* https://mitlibraries.atlassian.net/browse/ETD-374
NO
NO

Sets link to hold panel to open in new tab

---

app/views/thesis/_select_thesis.html.erb
app/views/thesis/select.html.erb

This adds the issues_found field to the thesis processing queue, and
renders the boolean value as "Yes" or "No" for legibility.
* https://mitlibraries.atlassian.net/browse/ETD-373
NO
NO

Adds an issues_found column to thesis queue

---

app/controllers/transfer_controller.rb
app/views/transfer/show.html.erb
test/controllers/transfer_controller_test.rb

* The list of files can be quite large in some cases
* Scrolling through files that have already been processed can be
annoying and inefficeint
* Most of the time, it is not useful to see the already assigned files
* https://mitlibraries.atlassian.net/browse/ETD-366
* Enables conditional display of the already assigned files during
the Transfer processing workflow
* The default is to not display assigned files
* Choosing to display assigned files should be sticking throughout the
processing of that Transfer but would need to be reapplied when
changing to a different Transfer. Being sticky beyond what we have
implemented here would require using a session …

Only display unassigned files by default

---

app/controllers/thesis_controller.rb
app/models/ability.rb
app/views/layouts/_site_nav.html.erb
app/views/thesis/_duplicate_thesis.html.erb
app/views/thesis/deduplicate.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb
test/fixtures/authors.yml
test/fixtures/theses.yml
test/integration/nav_test.rb

This implements a new view under the thesis model, `/thesis/deduplicate`. The layout of this view is very similar to the thesis processing queue, using DataTables for interactions with the displayed records.
The criteria for determining which records are displayed on this view are simple: does the thesis record have a populated "coauthor" field?
Records are displayed with a link to that thesis' processing form, allowing staff to modify records after analyzing each to determine which thesis should move forward into DSpace@MIT.
Further details of this work are in the linked ticket.
- https://mitlibraries.atlassian.net/browse/ETD-191
issues (link …

Implements a duplicate thesis report

---

app/views/thesis/_duplicate_thesis.html.erb

This changes the links on the duplicate thesis report. They currently point to the processing form, but Mikki provided feedback that this wasn't useful in this context. A better target is the administrate UI's edit thesis form, because this form allows the staff to add more author records.
https://mitlibraries.atlassian.net/browse/ETD-378
This is a mixing of the custom UI and the administrate UI, but I believe we already do this, and it seems more justifiable than building more custom UI elements.
NO
NO

Updates thesis links on duplicate report

---

README.md
app/views/transfer/new.html.erb

Following the decision to wrap up work on ETD-320, this is my attempt to cleanly finish the work-in-progress on an augmented file upload behavior.
This implements a switch in the new transfer form, activated by appending any value for `upload` to the querystring at the `/transfer/new` path (i.e. `/transfer/new?upload`). Adding this flag will activate the switch, which calls a different set of decoration functions.
These functions result in "remove" and "add more" controls appearing on the pending file list, allowing the user to append and remove files from the list before submitting the form.
**Please note!**
This work has gone through a fair amount of browser testing (Safari, Firefox, and Chrome on a Mac, and Edge on Windows), and some developer testing via WAVE and ANDI to confirm …

Add an augmented file upload behavior behind a querystring flag

---

app/models/thesis.rb
app/models/user.rb
test/models/thesis_test.rb
test/models/user_test.rb

Audit trails are needed for the User and Thesis models to enhance
registrar data import reporting.
https://mitlibraries.atlassian.net/browse/ETD-357
This adds papertrail to Thesis and User models.
As noted in the ticket, we may later want to expand papertrail to all
(or most) of the other models. For now, we are limiting scope to the
two models that directly affect the registrar data import.
NO
NO

ETD-357 Add papertrail to Thesis and User models

---

.codeclimate.yml

* The default rubocop for codeclimate is quite old
* rubocop was not enabled for this repo in codeclimate
* We'll need to manually bump the rubocop version in the codeclimate
config when we update rubocop and we won't be able to update rubocop
until codeclimate has a new channel for the new rubocop version
NO
NO

Configure codeclimate to use specific rubocop

---

Gemfile
Gemfile.lock
README.md
app/jobs/registrar_import_job.rb
app/mailers/report_mailer.rb
app/models/thesis.rb
app/views/report_mailer/registrar_import_email.html.erb
config/environments/development.rb
config/environments/production.rb
test/jobs/registrar_import_job_test.rb
test/mailers/report_mailer_test.rb
test/models/thesis_test.rb

Processors and thesis admins need to see summary data about the
registrar import job, especially if there are any issues with it.
The job currently logs much of this information, but an email report
would be more useful for stakeholders to review.
* https://mitlibraries.atlassian.net/browse/ETD-354
* https://mitlibraries.atlassian.net/browse/ETD-348
* https://mitlibraries.atlassian.net/browse/ETD-371
This adds some data collection to the import job, as well as a mailer
that reports the following data:
* Number of theses in the job
* Number of theses processed
* Errors found (total number and list)
* New DLCs added (total number and list)
* New degrees added (total number and list)
* Number of new users
* Number of new theses
* Number of updated theses
* The email is sent in the job rather …

Generate email report for data registrar import jobs

---

app/controllers/thesis_controller.rb
test/controllers/thesis_controller_test.rb

* Anytime a file is removed the thesis process should have to confirm
all files are complete
* https://mitlibraries.atlassian.net/browse/ETD-370
* Sets Thesis.files_complete to false when we remove files
* Files unattached not via the processing workflows will not reset the
files_complete flag
NO
NO

Resets files_complete when files are removed

---

app/views/report_mailer/registrar_import_email.html.erb

Stakeholder feedback on this email was to changing the wording from
'total theses' to 'total rows', as each row is not necessarily a
distinct thesis.
https://mitlibraries.atlassian.net/browse/ETD-354
This makes the requested changes.
None
NO
NO

ETD-354 Reword language in registrar import email

---

app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
app/views/thesis/process_theses.html.erb

This was additional stakeholder feedback on the student submission
form.
https://mitlibraries.atlassian.net/browse/ETD-390
This updates the creative commons link on the student submission
forms.
None at first, although the link is to a beta version of the site,
so we may need to update it in the future.
NO
NO

Change creative commons link

---

app/views/transfer/show.html.erb

This adds a class to the checkboxes in the list of files on a transfer processing form, along with some javascript that detects clicks on those checkboxes. The javascript will add a search/filter value to the table of thesis records, provided the table is currently unfiltered.
If the table is already filtered (either by this feature or via manual entry), no action is taken. We have no way of determining whether any filtering was done by the user or not, so it is better that we leave it alone - and let the user manipulate the filter value themselves.
- https://mitlibraries.atlassian.net/browse/ETD-367
issues (link to those issues in the Pull …

Filter list of theses on file selection during thesis processing

---

app/views/thesis/_select_empty.html.erb
app/views/thesis/_select_thesis.html.erb
app/views/thesis/select.html.erb
app/views/transfer/select.html.erb

This addresses a few different bugs that have been noticed in our DataTables implementation:
1. Both the Thesis and Transfer queues have a problem in how we've implemented the custom filtering buttons. The buttons do not persist their behavior beyond that click action, so re-sorting the table resets the filtering.
2. The Thesis queue, specifically, does not sort by degree date accurately - it uses an alphabetical sort rather than a date sort.
3. The "no records" display on the thesis queue has the wrong number of columns - we never bumped the colspan attribute when we added the issues found column.
Each of these is fixed in a separate commit, because they are separate bugs. I didn't create a separate ticket for the second and third items.
This code review is happening prior to stakeholder …

Fix sorting and filtering bugs in DataTables implementations

---

app/models/thesis.rb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
app/views/thesis/process_theses.html.erb

Abstract is currently a required field in the thesis submission forms,
but bachelor's theses don't require it.
https://mitlibraries.atlassian.net/browse/ETD-419
This removes the form validations that make abstract a required field.
None.
NO
NO

ETD-419 Make the abstract field optional in thesis forms

---

app/views/thesis/_select_empty.html.erb
app/views/thesis/_select_thesis.html.erb
app/views/thesis/select.html.erb

This was a requested change from the first round of thesis processing.
https://mitlibraries.atlassian.net/browse/ETD-352
This makes processor_note a searchable field in the thesis processing
datatable. We are leaving the column visible for now, but we may
need hide it later if it creates too much clutter in the UI. Jess will
keep an eye on this while processing theses.
This is the only text field that we are querying in the datatable,
so it's an open question as to whether this will perform adequately
at scale. We can adjust as needed based on what we see in prod.
(not just this …

ETD-352 Add processor note to searchable fields in thesis processing queue

---

app/models/dspace_metadata.rb
test/fixtures/users.yml
test/models/dspace_metadata_test.rb

We want to be able to publish theses to DSpace, which requires
us to convert relevant thesis metadata to DSS-compliant JSON.
* https://mitlibraries.atlassian.net/browse/ETD-394
This creates the requisite submission metadata for DSS, based on the
submission message spec and the data mappings spreadsheet. It does not
save said metadata to AWS, nor does it write messages to the queue.
I'm open to including that work in the same PR, but this seeemed like
a logical breakpoint.
There are fields that are required for publication that are not
validated anywhere in the application. The current process is for
Jess to confirm these as part of their workflow, but we should make
their life easier by including an automated check as part of
the publication status update workflow. A ticket for this work …

Construct DSS JSON

---

app/dashboards/copyright_dashboard.rb

* The administrate page for License currently displays a panel of theses
which have that license, but the admin page for Copyright does not.
Stakeholders have requested that the Copyright page be made to match
the License page.
* https://mitlibraries.atlassian.net/browse/etd-411
* This adds "theses" to the list of information displayed on the admin
Copyright page
* None
NO
NO

Adds list of theses to admin copyright page

---

app/models/user.rb
test/models/user_test.rb

This extends the (existing) `editable_theses` helper method on the user model, adding a second condition - that theses are only editable if _both_ the `metadata_confirmed` and `issues_found` flags are both set to `FALSE` (which is the default condition.
https://mitlibraries.atlassian.net/browse/ETD-305
NO
NO*
(An earlier version of this PR had added Timecop, but that has now been removed)

Prevents student editing of thesis metadata when issues have been flagged

---

app/assets/stylesheets/thing.scss
app/controllers/report_controller.rb
app/controllers/thesis_controller.rb
app/dashboards/thesis_dashboard.rb
app/helpers/thesis_helper.rb
app/models/ability.rb
app/models/report.rb
app/models/thesis.rb
app/views/layouts/_site_nav.html.erb
app/views/report/_card.html.erb
app/views/report/_table.html.erb
app/views/report/index.html.erb
app/views/shared/_defined_terms_filter.html.erb
app/views/shared/_report_submenu.html.erb
app/views/thesis/deduplicate.html.erb
app/views/thesis/select.html.erb
config/routes.rb
test/controllers/report_controller_test.rb
test/helpers/thesis_helper_test.rb
test/integration/nav_test.rb
test/models/thesis_test.rb

This creates the first summary dashboard for thesis records (for a given term). It contains the data points asked for in ETD-412, with links to see more information for various subsets of records.
1. The total number of thesis records (with a link to see them in the admin dashboard)
2. The number of theses which have attached files (and a link to see them in the processing queue)
3. The number of theses which have been flagged as having issues (there is no link for this box, because there's no easy web address to surface them - you would need to enter a filter value in the processing queue)
There are also two breakdown tables, showing how many thesis records are in each of two categories: publication status and copyright holder. The ticket only asks for publication status, but a separate …

Initial reporting dashboard

---

app/models/report.rb
app/views/report/_card.html.erb
config/initializers/inflections.rb
test/controllers/report_controller_test.rb
test/models/report_test.rb

This adds three new cards to the thesis dashboard, counting how many theses have multiple affiliated subrecords:
* Theses with multiple authors
* Theses with multiple degrees
* Theses with multiple departments
https://mitlibraries.atlassian.net/browse/ETD-414
NO
NO

Adds reporting cards for theses with multiple subrecords

---

app/models/thesis.rb
test/fixtures/degrees.yml
test/models/dspace_metadata_test.rb
test/models/thesis_test.rb

This is additional work toward ETD-394, which involves creating
a DSS-compliant JSON package and submitting a message to the SQS
queue. This particular commit associates metadata JSON objects
with Thesis records, and puts the metadata files in place in S3.
https://mitlibraries.atlassian.net/browse/ETD-394
This uses Active Storage to attach metadata JSON (i.e., DspaceMetadata
objects) to their Thesis records and upload them to S3. The next
step is to build the SQS message and the job that puts it all together
and submits it to the SQS queue.
We're using StringIO to simulate IO on the serialized JSON string, so
Active Storage will attach it as a file. This doesn't affect the
outcome, but it's worth noting as a fairly unusual approach.
[our …

ETD-394 Upload DSS metadata JSON files to S3

---

app/models/dspace_metadata.rb
app/models/sqs_message.rb
config/environments/test.rb
test/fixtures/degrees.yml
test/models/sqs_message_test.rb

This is the third part of ETD-394, supporting publication to
DSpace@MIT via the DSpace Submission Service.
https://mitlibraries.atlassian.net/browse/ETD-394
This constructs the SQS message attributes and body, as per the
DSS spec. Submitting the message to the queue will come in a
subsequent PR.
None.
NO
NO

ETD-394 Construct DSS SQS message

---

app/controllers/report_controller.rb
app/models/ability.rb
app/models/report.rb
app/views/report/_files_empty.html.erb
app/views/report/_files_without_purpose.html.erb
app/views/report/files.html.erb
app/views/shared/_report_submenu.html.erb
config/routes.rb
test/controllers/report_controller_test.rb

This adds a new report page for files with no defined purpose. The table includes links to the processing form for that thesis, so staff can assign a purpose.
More details in the commit message...
https://mitlibraries.atlassian.net/browse/ETD-418
NO
NO

Adds report for thesis files with no defined purpose

---

app/controllers/thesis_controller.rb
app/models/ability.rb
app/models/thesis.rb
app/views/thesis/select.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb
test/models/thesis_test.rb

This augments the Thesis Processing Queue, adding a button that will publish records in the `Publication Review` status to our repository via the coming DSpace Submission Service.
As yet, this button does not do anything - but it will. Clicking the button with this PR will generate a flash message that is a placeholder.
I've populated a sample record in the review app, in case you want to see how the button appears / disappears.
https://mitlibraries.atlassian.net/browse/ETD-310
NO
NO

Adds "Publish to DSpace@MIT" button to processing queue

---

app/views/thesis/deduplicate.html.erb
app/views/thesis/select.html.erb
app/views/transfer/select.html.erb
app/views/transfer/show.html.erb

This enables the `stateSave` parameter on all four implementations of the DataTable library across the app:
* Thesis processing queue
* Transfer processing queue
* Transfer processing form
* Deduplication report
It further integrates the custom filter buttons which have been added to the two processing queues.
Along the way, this PR also updates DataTables to the current release (1.11.3, from 1.10.24). I debated making the implementation itself more robust by looking for a Rails gem that might include it, or doing more with WebPacker, but elected against this for now.
https://mitlibraries.atlassian.net/browse/ETD-440
issues (link to those …

Enable state saving on Thesis and Transfer processing queues

---

app/controllers/report_controller.rb
app/models/ability.rb
app/models/report.rb
app/views/report/_files_empty_proquest.html.erb
app/views/report/_files_proquest_form.html.erb
app/views/report/proquest_files.html.erb
app/views/shared/_report_submenu.html.erb
config/routes.rb
test/controllers/report_controller_test.rb

Thesis processors need to be able to download ProQuest forms.
https://mitlibraries.atlassian.net/browse/ETD-481
This creates a report that lists the theses with ProQuest forms.
Each row includes a clickable link of the ProQuest form for processors
to download.
Adds a new route and modifies the ability model to account for the
new controller action.
NO
NO

ETD-481 Add report for thesis with ProQuest forms

---

app/models/ability.rb
test/integration/admin/admin_thesis_test.rb

Originally, thesis admins were not allowed to delete theses, but
there are certain situations in which they need to (e.g., duplicate
thesis records).
https://mitlibraries.atlassian.net/browse/ETD-482
This updates the abilty model to allow thesis admins to delete theses.
None.
NO
NO

ETD-482 Allow thesis_admin role to delete theses

---

test/controllers/report_controller_test.rb
test/controllers/thesis_controller_test.rb
test/fixtures/active_storage/attachments.yml
test/fixtures/active_storage/blobs.yml
test/models/report_test.rb
test/models/thesis_test.rb
test/models/transfer_test.rb

This updates our thesis fixtures - as well as one transfer fixture - to have files attached without needing to rely on a `setup` method, or a helper function to do during a test. The work was motivated by some work on ETD-415 and ETD-477, where I realized that having test fixtures with files already attached could be helpful.
Some tests will need files to be attached _during_ the test, so some of these helper functions still remain (and are called).
Additionally, because this work has so far been focused on thesis testing, I've not yet extended this work to update other fixtures - for example, the Registrar fixtures, department tests, and a few others. Searching the test directory for the `.attach` method gives a sense of how much is still being done that way.
I welcome feedback from the …

Update thesis fixtures to have files attached automatically

---

app/jobs/dspace_publication_job.rb
app/jobs/dspace_publication_results_job.rb
test/jobs/dspace_publication_job_test.rb
test/jobs/dspace_publication_results_job_test.rb

In its current state, the app does not send mail if the DSpace
Publication Results Job is run and the results include errors only.
This is because mail is sent when results[:processed] is positive,
and this condition will never be met if the job returns no successes.
https://mitlibraries.atlassian.net/browse/ETD-502
This changes the condition for the DSpace Publication Results Job
to send mail. Mail will now be sent either if results[:total] is
positive, or if results[:errors] has any items. The results[:errors]
piece of this is necessary because the job can fail before it starts
polling, in which case results[:total] will not increment.
I noticed some TODOs in the DSpace Publication Job around setting
the publication status to 'Publication error'. It seems we didn't
have that status in …

ETD-502 Fix mailer bug in DSpace Publication Results Job

---

app/models/sqs_message.rb
test/models/sqs_message_test.rb

* Only the thesis PDF and any supplementary files should be sent to
DSpace - the source files, signature pages, and proquest forms should
not.
* https://mitlibraries.atlassian.net/browse/etd-500
* This adds a small select() clause to the SQS Message model's map_files
method, such that only those two types of files are added to the
package.
* None, that I'm aware of. I worry slightly about what changes may be
needed when we start publishing to more than just DSpace, but the
map_files method can probably be split to a filter_for_dspace()
and filter_for_archivespeace() or something. …

Publish only PDF and supplementary files via SQS

---

app/assets/stylesheets/thing.scss
app/views/thesis/_degree_fields.html.erb
app/views/thesis/process_theses.html.erb

Theses require degrees and advisors to be valid for publication,
but it's not clear in the UI when a thesis is missing these fields
because the form hides them if they are empty.
https://mitlibraries.atlassian.net/browse/ETD-476
This adds read-only values for the advisor and degree form elements
that inform the user if the thesis has no associated advisors or
degrees.
* I refactored the degree field UI to a partial, as the additional logic
complicated it enough to warrant it.
* The advisor field refactor removes the association link, since this
creates some complications with the read-only field. I added a hint
with a link to the edit admin path so processors can add advisors
there.
all issues introduced by these …

ETD-476 Clearly show absence of degrees and advisors in processing form

---

app/assets/stylesheets/thing.scss
app/views/thesis/publish_preview.html.erb

* During QA testing for ETD-477, Jess asked that the final banner and
button that will initiate the publication process be rendered with a
color, to call out that this is something different than normal
processing. The goal is to prevent accidental clicking.
* Our current theme gem does not implement a coloring option for this
"well" element, although elsewhere it does define semantic colors for
"warning", "error", and "success".
* https://mitlibraries.atlassian.net/browse/etd-477
* This extends our application of the warning, error, and success colors
to the styles for the "well" elements, so that .well.success will, for
example, produce a well box that is shaded green. .well.warning will
render with a yellow treatment, and .well.error will render with a red
treatment.
* Given these new …

Adds color to final banner of publication UI

---

app/models/dspace_metadata.rb
test/models/dspace_metadata_test.rb

DSpace does not support UTF-8 codes or HTML entities, so the
only way to display a copyright symbol is to use the UTF-8
character itself.
https://mitlibraries.atlassian.net/browse/ETD-515
This uses the UTF-8 character in the Dspace Metadata mdoel instead
of the UTF-8 code.
None expected, but we'll need to determine whether this will publish
successfully. I've confirmed that DSpace test renders the character
when editing the record metadata in the DSpace UI, but I haven't
confirmed that the full publication workflow will run as expected.
NO
NO

ETD-515 Use UTF-8 character instead of code for copyright symbol

---

app/jobs/dspace_publication_results_job.rb

When the DSpace Publication Results Job sees a record with a result
type of error, it adds the exception message and the thesis ID to
the errors array. We've seen at least once instance where the result
type is error but the exception message is empty, which results in
an unhelpful message like this: " (thesis ID 42)".
https://mitlibraries.atlassian.net/browse/ETD-510
This adds a bit more context to the error message described above,
so can determine the following:
1. That DSS encountered an error while processing the record; and
2. What the publication status was updated to (hopefully 'error').
This will change (i.e., enrich) how errors are reported in the
publication results email.
all issues introduced by these …

ETD-510 Further describe DSS status errors

---

app/dashboards/thesis_dashboard.rb
test/integration/admin/admin_thesis_test.rb

Ordinarily dspace_handle will be automatically generated as part of
the publication workflow, but there are some cases in which a thesis
must be published manually, which would require the processor to input
the handle in administrate.
https://mitlibraries.atlassian.net/browse/ETD-519
This makes dspace_handle a form attribute in the administrate thesis
dashboard.
None.
NO
NO

ETD-519 Add dspace_handle to administrate thesis dashboard

---

app/assets/stylesheets/thing.scss
app/controllers/thesis_controller.rb
app/helpers/thesis_helper.rb
app/models/ability.rb
app/views/shared/_report_submenu.html.erb
app/views/thesis/_publication_status_filter.html.erb
app/views/thesis/_thesis_publication_status.html.erb
app/views/thesis/publication_statuses.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb
test/helpers/thesis_helper_test.rb

Processors need a report that clearly shows the current publication
status of the theses in the application.
https://mitlibraries.atlassian.net/browse/ETD-315
This creates a report that lists theses' current publication statuses.
The report includes param filters to optionally refine the results by
term, publication status, or both. DataTables is included for additional
filtering if needed.
Adds a CSS rule to create some spacing between the two selects.
NO
NO

ETD-315 Add report on theses by publication status

---

app/models/dspace_metadata.rb
test/models/dspace_metadata_test.rb

We learned that unicode characters are not accepted by
Archivematica.
https://mitlibraries.atlassian.net/browse/ETD-515
We are not printing the word 'Copyright' instead of the
unicode character.
None.
NO
NO

ETD-515 Don't use copyright unicode character

---

app/models/thesis.rb
app/views/thesis/_degree_fields.html.erb
app/views/thesis/process_theses.html.erb
test/models/thesis_test.rb

* There is no clear indication of issues with associated Departments
or Degrees on the Thesis processing pages. These issues _will_ prevent
a Thesis from being published so it makes sense to inform at this
stage so the Processor can resolve the issues proactively rather than
find out about them during failed publication attempts.
* https://mitlibraries.atlassian.net/browse/ETD-517
* https://mitlibraries.atlassian.net/browse/ETD-518
* Creates checks for missing Degree types and Department.name_spaces
* Updates the publication review checks to include these new checks
* Displays messages inline on the Thesis processing page near where
a processor would be looking at this information anyway so they …

Warn for Degree and Dept issues when Processing

---

app/models/dspace_metadata.rb
app/models/license.rb
test/models/dspace_metadata_test.rb
test/models/license_test.rb

During publication workflow testing, stakeholders noted that "No
Creative Commons" looks odd in DSpace, and it would be preferable
for these license types to read as "In Copyright -- Educational Use
Permitted" instead.
https://mitlibraries.atlassian.net/browse/ETD-514
This adds a method to the license model that returns the desired
phrase for "No Creative Commons" license types, and otherwise
returns the license type as stored in the database. We then use
that method in the Dspace Metadata model to ensure that the mapped
value appears in DSpace.
This change complicates the testing approach we use for the Dspace
Metadata model, which effectively checks for all possible values of
dc.rights in the unserialized metadata against a given thesis'
copyright and license. Now that we are using the …

Add text mapping for "No Creative Commons" license type

---

app/controllers/report_controller.rb
app/models/report.rb
app/models/thesis.rb
app/views/report/index.html.erb
app/views/report/student_submitted_theses.html.erb
app/views/report/term.html.erb
app/views/shared/_whodunnit_accuracy_statement.html.erb
test/controllers/report_controller_test.rb
test/controllers/thesis_controller_test.rb
test/integration/thesis_test.rb
test/models/thesis_test.rb

This adds information about how many theses have had contributions from students to the reporting dashboard, as well as to the term detail report.
See the commit message for a list of concerns that I'm having trouble shaking out of my head.
https://mitlibraries.atlassian.net/browse/ETD-415
NO
NO

Adds count of student contributions to dashboard and term report

---

README.md
lib/tasks/dss.rake

* We need a way to run the output processing job
* https://mitlibraries.atlassian.net/browse/ETD-501
* Creates a rake task to allow us to easily trigger the job to run on
Heroku from our local CLI rather than having to create a console
session in Heroku to run job
If multiple apps are connected to the same output queue
(such as local dev and staging), running in one (such as local dev) will
only update the local instance but possibly be processing output for
different environemnts. In practice, this should not be a risk in
production as nobody should have configuration locally to connect to
production output queues so the risk is more associated with PR …

Adds a rake task for processing dss output queue

---

app/assets/stylesheets/thing.scss
app/controllers/report_controller.rb
app/models/ability.rb
app/models/hold.rb
app/models/report.rb
app/views/report/_expired_holds_empty.html.erb
app/views/report/_expired_holds_row.html.erb
app/views/report/expired_holds.html.erb
app/views/shared/_report_submenu.html.erb
app/views/transfer/_welcome.html.erb
config/routes.rb
test/controllers/report_controller_test.rb
test/models/hold_test.rb

This creates a report of holds which should be reviewed for a status change: holds with an end date of today or before, and which have not yet been marked as "released" (i.e. either "active" or "expired"). Each hold displayed is linked to its administrative form, so staff can make any adjustments needed.
We have now gotten some confirmation in the Jira ticket that the assumptions in this work (laid out in the Jira thread) are acceptable to Jess - so I'm marking the "stakeholder approval" box as true.
https://mitlibraries.atlassian.net/browse/ETD-453
(not just this pull request …

Report on expired holds

---

app/jobs/dspace_publication_results_job.rb
test/fixtures/active_storage/blobs.yml
test/jobs/dspace_publication_results_job_test.rb

* It is important that we validate the files we publish are the same as
the files we intended to publish. DSpace is already providing DSS with
checksums that DSS provides to ETD. This just implements validating
the checksums that DSpace sends back with the checksums ETD already
stores as part of ActiveStorage.
* https://mitlibraries.atlassian.net/browse/ETD-523
* Validates that checksums coming back from DSS are valid for the Thesis
being published.
* Sets theses to error state, logs errors, and alerts stakeholders if
errors are detected so they can resolve them manually
all issues introduced by these changes have been …

Validate checksums in Publication Results Job

---

README.md

The SQS configuration section of the readme does not include the
required field of `SQS_OUTPUT_QUEUE_URL`.
None.
This adds the missing info to the readme.
None.
NO
NO

Update SQS config documentation

---

app/models/dspace_metadata.rb
app/models/license.rb
test/models/dspace_metadata_test.rb
test/models/license_test.rb

In the DspaceMetadata class, we map thesis records with author
copyright and no CC license to a dc.rights value of “In Copyright -
Educational Use Permitted.” However, because the no-CC license
record has no URL associated, these thesis records show up in
DSpace with no dc.rights.uri field. We want the dc.rights.uri
field to match the statement, so we need to associate this rights
URL with no-cc license theses: 'In Copyright - Educational Use
Permitted | Rights Statements'.
https://mitlibraries.atlassian.net/browse/ETD-534
This adds an evaluate_license_url method to the License model that
returns the desired URL if the corresponding license_type is equal
to "No Creative Commons License". This method is then invoked in
DspaceMetadata#copyright, in the condition branch for which the
author …

Add license URL to theses with no-CC license

---

README.md
lib/tasks/dss.rake

* Publishing a full batch without being able to test a single
thesis is inherently risky and should be avoided.
* There may also be cases where we want to publish a single thesis a bit
early and this would support that.
* https://mitlibraries.atlassian.net/browse/ETD-535
* Provides a rake task that can be run through the Heroku console to
publish a single already publishable thesis
NO
NO

Provides a rake task to publish a single thesis

---

Gemfile
Gemfile.lock
README.md
app/controllers/thesis_controller.rb
app/models/report.rb

* There were multiple N+1 queries that when combined with production
data led to Heroku timeouts
* https://mitlibraries.atlassian.net/browse/ETD-550
* https://mitlibraries.atlassian.net/browse/ETD-551
* eager load the relevant data to eliminate the N+1 problems
NO
YES

Resolve N+1 queries in pub status report and index

---

app/jobs/dspace_publication_results_job.rb
app/lib/checksums.rb
app/models/bag.rb
test/fixtures/theses.yml
test/models/bag_test.rb

We need a data structure that creates the foundation for preservation
bags.
https://mitlibraries.atlassian.net/browse/ETD-530
This creates a Bag model that takes a thesis and generates generates
a bag declaration, manifest and bag name for it. It also includes
a `data` method that returns a hash of filepaths for the bag's data
directory, along with their corresponding blobs.
* The base64_to_hex method has been moved to a new Checksums module,
as it is now used both in the publication results job and in this
new model. We may choose to move additional checksum logic to this
module if it is required in multiple places.
* Once ETD-529 is complete, we will need to build the metadata CSV
in this class and add it to the data hash. It's possible this can
all happen within the `data` method, …

Create structure for BagIt bags

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
README.md
test/jobs/registrar_import_job_test.rb
test/test_helper.rb

* we have a few really slow tests that are in isolated pieces of code
that are useful to have around but are annoying during most
development
* Adds two environment settings that control the test formating and
whether to skip tests defined as slow (as of this commit, only one is
flagged as slow)
* This sets Actions to use a more detailed report of all the tests
instead of the terse default version and allows developers to use the
version they prefer locally
* The defaults do not change for either of these new settings, other
than in Actions where this commit includes explicitly setting the
test reporter to use the SpecReporter
* The skipped tests are a bit more obvious when …

Optional settings for test runs

---

Gemfile
Gemfile.lock
app/models/submission_information_package.rb
app/models/submission_information_package_zipper.rb
test/models/submission_information_package_test.rb
test/models/submission_information_package_zipper_test.rb

* delivery of a bag to s3 is how we are handling preservation
* https://mitlibraries.atlassian.net/browse/ETD-531
* https://mitlibraries.atlassian.net/browse/ETD-558
* Creates a temporary zip file on disk and streams objects for a thesis
into that tempfile
* Attaches that tempfile via ActiveStorage to a newly created
SubmissionInformationPackage
* This uses Heroku's filesystem to store the tempfiles to create the zip
which is non-ideal but because this all happens in a single event it
should be safe to do this. The use of a tempfile ensures the file is
deleted when the handle is closed so if this occurred over multiple
requests it would already fail for …

Create and attach zipped bag to SIP

---

README.md
app/jobs/preservation_submission_job.rb
app/jobs/preservation_submission_prep_job.rb
app/models/submission_information_package.rb
lib/tasks/preservation.rake
test/jobs/preservation_submission_job_prep_test.rb
test/jobs/preservation_submission_job_test.rb
test/models/submission_information_package_test.rb
test/models/submission_information_package_zipper_test.rb

We need a way to initiate SIP creation, bagging and streaming to
S3.
https://mitlibraries.atlassian.net/browse/ETD-553
This creates two jobs:
1. PreservationSubmissionJob attempts to send a single thesis to
preservation and modifies the preservation_status and preserved_at
fields accordingly.
2. PreservationSubmissionPrepJob loops through an array of theses
to preserve.
* preservation_status is now an enum with three options: unpreserved
(the default), preserved, and error.
* Adds `preservation.rake` task to send a single thesis to
preservation via Rails CLI.
(not just this pull …

Create batch jobs for preservation

---

app/jobs/dspace_publication_results_job.rb
app/views/report_mailer/publication_results_email.html.erb
test/jobs/dspace_publication_results_job_test.rb

We need to automate the preservation workflow.
https://mitlibraries.atlassian.net/browse/ETD-560
* Collects valid theses from the DspacePublicationResultsJob SQS
queue as `results[:preservation_ready]`.
* Enqueues PreservationSubmissionPrepJob with preservation-ready
theses.
* Reports total number of theses submitted to preservation in
publication results job email.
Now that we're tying the preservation workflow into the publication
workflow, there is likely some duplication in our validations.
Specifically, `SubmissionInformationPackage#baggable_theses?` checks
for things that are also validated in DspacePublicationResultsJob.
This may be a useful failsafe rather than potentially harmful
duplication, but I wanted to bring it to the reviewer's attention.
[our …

Enqueue preservation job within publication results job

---

app/views/report_mailer/publication_results_email.html.erb
test/mailers/report_mailer_test.rb

The publication results email shows the full array of preserved
thesis. It should show the total count instead.
N/A.
This changes the publication results email view to render the count
of preserved theses.
None.
NO
NO

Show count of preserved theses in publication results email

---

README.md

To provide documentation for developers on how and when various types of data get loaded into the system.
* Adds a Data Loading section to the README with documentation on seed data and registrar data loads, and a placeholder for test data loads
None
* https://mitlibraries.atlassian.net/browse/ETD-217
NO
NO

Add data loading documentation to README

---

app/controllers/admin/submission_information_packages_controller.rb
app/dashboards/submission_information_package_dashboard.rb
app/dashboards/thesis_dashboard.rb
app/models/ability.rb
app/views/fields/attachment_field/_show.html.erb
config/routes.rb
test/controllers/report_controller_test.rb
test/fixtures/active_storage/attachments.yml
test/fixtures/submission_information_packages.yml
test/fixtures/theses.yml
test/integration/admin/admin_submission_information_package_test.rb

* Being able to see the SIPs for a Thesis as well as all of the SIPs
will be useful to better understand the state of Preservation
* https://mitlibraries.atlassian.net/browse/ETD-562
* Adds link to SIP(s) from the Thesis show pages
* Adds a new SIP Dashboard to view all SIPs
* Some tests around reports got updated with a new value to account for
a change to fixtures
* Our custom field for ActiveStorage in Administrate got a bit weirder
to handle the difference between HasOne and HasMany ActiveStorage
relationships
all issues introduced by these changes have been resolved or opened as …

Adds Administrate Dashboard for SIPs

---

app/models/thesis.rb
test/models/thesis_test.rb

* Initially, we need a way to identify Theses that we have published
before we had Preservation was completed and this should make it easy
to do that
* Longer term, this feels like a set of queries that might be useful in
reports to make it more visible if anything didn't get preserved
during the publication process
* https://mitlibraries.atlassian.net/browse/ETD-563
* adds scopes and tests to confirm they are accurate
NO
NO

Adds Thesis scopes for sips

---

app/models/submission_information_package.rb
test/models/submission_information_package_test.rb

The preservation package spec requires that metadata files be
stored as `data/metadata/metadata.csv`, but they are currently
stored as `data/metadata.csv.
https://mitlibraries.atlassian.net/browse/ETD-564
This fixes the location of the metadata CSV in the
SubmissionInformationPackage model.
None.
NO
NO

Update location of metadata CSV in SIPs

---

README.md
app/jobs/dspace_publication_results_job.rb
app/jobs/marc_export_job.rb
app/mailers/batch_mailer.rb
app/models/marc_batch.rb
app/views/batch_mailer/marc_batch_email.html.erb
app/views/report_mailer/publication_results_email.html.erb
config/environments/test.rb
test/jobs/dspace_publication_results_job_test.rb
test/jobs/marc_export_job_test.rb
test/mailers/batch_mailer_test.rb
test/mailers/report_mailer_test.rb
test/models/marc_batch_test.rb

We need an automated way to export published records as MARC and
send them to the cataloging team.
https://mitlibraries.atlassian.net/browse/ETD-564
* Adds a MarcBatch model that builds a compressed marcxml
file from an array of theses.
* Adds a BatchMailer that attaches a compressed marcxml file
built by the MarcBatch model and sends it to the cataloging
team.
* Adds a MarcExportJob that takes an array of theses, builds
a marcxml file for them, and sends a BatchMailer email.
* Updates DspacePublicationResultsJob to run MarcExportJob for
all published theses in the results queue.
* MarcExportJob doesn't employ the 'prep job' pattern that we use
elsewhere. It didn't seem necessary here to differentiate between
processing a single thesis versus an array, since I couldn't
figure a use case …

Implement MARC export workflow

---

app/controllers/report_controller.rb
app/helpers/hold_helper.rb
app/models/ability.rb
app/models/report.rb
app/views/report/_hold.html.erb
app/views/report/_hold_empty.html.erb
app/views/report/_holds_by_source_filter.html.erb
app/views/report/holds_by_source.html.erb
app/views/shared/_report_submenu.html.erb
config/routes.rb
test/controllers/report_controller_test.rb

We need to be able to see the holds for a given degree period,
filtered by hold source.
https://mitlibraries.atlassian.net/browse/ETD-462
This adds a report of holds that allows filtering on thesis
grad date and hold source.
* Report#extract_terms now checks for the type of items in the
collection, so as to accommodate non-thesis collections.
NO
NO

Add holds by source report

---

app/controllers/report_controller.rb
app/models/ability.rb
app/models/report.rb
app/models/thesis.rb
app/views/report/_not_graduated.html.erb
app/views/report/_not_graduated_empty.html.erb
app/views/report/authors_not_graduated.html.erb
app/views/shared/_report_submenu.html.erb
config/routes.rb
test/controllers/report_controller_test.rb

We need to identify thesis records that have files attached and
one or more authors without confirmed graduation
https://mitlibraries.atlassian.net/browse/ETD-429
This adds an 'authors not graduated' report that is term-filterable.
N/A.
NO
NO

Report for authors without confirmed graduation

---

app/models/report.rb

QA on #916 revealed a discrepancy between the number
of authors not graduated in the summary report and
the authors not graduated report. This is because we
were not deduping thesis records in
Report#data_authors_not_graduated.
https://mitlibraries.atlassian.net/browse/ETD-429
In Report#data_authors_not_graduated, this calls `select` instead
of `map` to identify ungraduated authors, then calls `uniq` on the
result to avoid counting duplicate records.
This went unnoticed until QA in part because we do not extensively
test the summary report. It's probably okay to test that feature
minimally since this sort of thing is likely to be caught by
stakeholders, but we should consider extending unit testing for
reporting if it happens again.
[our …

Fix bug in summary report for authors not graduated

---

app/models/report.rb
test/models/report_test.rb

Report#data_authors_not_graduated does not include a grad_date filter,
so all theses with ungraduated authors are shown for each term
instead of just the theses for the corresponding term.
https://mitlibraries.atlassian.net/browse/ETD-429
This adds the term filter into Report#data_authors_not_graduated
N/A.
NO
NO

Add term filter to summary of authors_not_graduated data

---

app/models/report.rb
test/models/report_test.rb

Theses with multiple files are being counted for each attached
file in the authors not graduated summary data.
https://mitlibraries.atlassian.net/browse/ETD-429
This dedups theses to fix the count in the Report index.
N/A.
NO
NO

Dedup authors not graduated summary data

---

app/models/thesis.rb
test/models/thesis_test.rb

When a thesis is saved, Thesis#evaluate_status will not evaluate as
expected, due to certain convenience methods used within
`Thesis#required_fields?`. These methods return the wrong value
before the record is saved, requiring processors to submit the
processing form twice in order to update a thesis' publication status.
Because we use the `before_save` callback, this bug can also occur if
nested attributes are updated, but the Thesis model is not (e.g.,
a new degree is attached, but none of the thesis attributes are
changed). This means that the thesis record is not technically saved,
and the `before_save` callback won't fire.
https://mitlibraries.atlassian.net/browse/ETD-507
* Updates the logic in `Thesis#advisors?` and `Thesis#degrees?`
to use `any?` rather than `count.zero?`, which …

Fix publication status update logic

---

app/dashboards/thesis_dashboard.rb
app/models/thesis.rb
db/migrate/20220329202143_remove_status_from_thesis.rb
db/schema.rb
test/fixtures/theses.yml
test/models/thesis_test.rb

The status field is no longer used in the new application.
https://mitlibraries.atlassian.net/browse/ETD-94
This removes the status field.
None.
YES
NO

Remove status field from Thesis model

---

config/initializers/devise.rb

We are seeing clock drift issues in authentication.
This is a quick fix that seems to resolve it. I'll open a ticket to dig in deeper but want to resolve the production bug asap first.

testing allowing more clock drift during auth

---

app/assets/stylesheets/thing.scss
app/controllers/thesis_controller.rb
app/dashboards/author_dashboard.rb
app/helpers/thesis_helper.rb
app/models/thesis.rb
app/views/thesis/_author_fields.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
db/migrate/20220826202539_add_proquest_allowed_to_authors.rb
db/schema.rb
test/helpers/thesis_helper_test.rb
test/integration/thesis_test.rb
test/models/author_test.rb

We need to document permission from authors of graduate theses as to whether we can send their theses to ProQuest or not.
https://mitlibraries.atlassian.net/browse/ETD-587
This adds a proquest_allowed boolean field to the author model thesis and adds it as a field to the new and edit thesis forms. As per the ticket requirements, this field only shows in the edit form for graduate degree types. Null values are allowed in the data model, but the field is validated in the form.
* The new field has been added to the author administrate dashboard. This was not specified in the success criteria, but it seemed like it would be useful to processors.
* The new form element will need UXWS review before we deploy it to production.
[our guide](https://mitlibraries.github.io/guides/basics/a11y.html) …

Add ProQuest opt-in to thesis submission forms

---

app/views/thesis/_welcome.html.erb

The welcome partial asks students to send the ProQuest form directly to their departments. This will now be integrated into the student submission form.
* https://mitlibraries.atlassian.net/browse/ETD-601
This removes the ProQuest form text from the welcome partial.
None.
NO
NO

Remove ProQuest reference from student submission welcome partial

---

app/helpers/thesis_helper.rb
test/controllers/report_controller_test.rb
test/helpers/thesis_helper_test.rb

The param to filter published theses in
ThesisHelper#filter_published_by_thesis is currently named `published`. This is an ambiguous name for the param. When it is set to false, the helper method returns all theses, including those that are published. However, `published=false` would indicate a result set that excludes published theses.
https://mitlibraries.atlassian.net/browse/ETD-591
https://mitlibraries.atlassian.net/browse/ETD-599
This renames the param to `published_only`, which more clearly articulates what it's supposed to do.
None.
NO
NO

Rename published param in ProQuest report

---

app/views/report/_proquest_status_filter.html.erb

The proquest status filter partial still uses param[:published] instead of param[:published_only], so the radio buttons do not work as expected.
* https://mitlibraries.atlassian.net/browse/ETD-591
* https://mitlibraries.atlassian.net/browse/ETD-599
This updates the partial to use the correct param.
None.
NO
NO

Update filter partial to use published_only param

---

app/assets/stylesheets/thing.scss
app/views/thesis/_author_fields.html.erb

During a11y review, we determined that interactive content is not advisable inside a label. Anchors and other interactive elements can confuse screen reader navigation within the label, and make it difficult for people to activate the corresponding form input.
https://mitlibraries.atlassian.net/browse/ETD-602
This moves the bulk of the descriptive content outside of the field label, so the label is more direct in what it is asking of the user. This also adds a header to the ProQuest field, which Dhruti recommended.
None.
NO
NO

Move descriptive text of ProQuest opt-in outside of field label

---

app/views/report/proquest_status.html.erb

The ProQuest opt-in status report only lists theses with advanced degrees and files attached. These conditions are not clear in the current UI.
https://mitlibraries.atlassian.net/browse/ETD-604
This adds an alert banner clarifying the scope of the report.
None.
NO
NO

Add scope note to ProQuest opt-in status report

---

app/models/transfer.rb
test/integration/transfer_test.rb

**NOTE: You can test this manually by creating a Transfer with a file in Stage and noting it shows up as 0/1 in the Transfer Select page and comparing that to the PR build or locally doing the same should show up as 1/1 (or 5/5 if you upload five files, etc)**
**Note: we'll want to run the rake task in production after this merges to ensure any Transfers created between when this bug occurred and now are updated with proper counts**
* unassigned_files_count was not updated for newly created Transfers due to how ActiveStorage objects are not available until the `after_create_commit` callback
* https://mitlibraries.atlassian.net/browse/ETD-613
* Adds an `after_create_commit` to Transfers that …

Ensure updated counts for new Transfers

---

README.md
app/mailers/application_mailer.rb
app/mailers/batch_mailer.rb
app/mailers/receipt_mailer.rb
app/mailers/report_mailer.rb
config/environments/test.rb
test/mailers/batch_mailer_test.rb
test/mailers/receipt_mailer_test.rb
test/mailers/report_mailer_test.rb

The 'from' and 'to' addresses are currently the same, which causes an unwanted loop in libanswers.
https://mitlibraries.atlassian.net/browse/ETD-618
This sets the 'form' address in all mailers to a new env, ETD_APP_EMAIL.
The new env will need to be added to all pipelines.
NO
NO

Change email 'from' address

---

app/controllers/thesis_controller.rb
app/models/thesis.rb
test/models/thesis_test.rb

This is a similar issue to the one solved in #1108, but in the not_consented_to_proquest scope. Here, the scope excludes all theses with an author ProQuest consent value of 'true'. This works in most cases, except when one author has opted in and another hasn't, that thesis should still be partially harvested. With the current logic, it will not show up in the export preview because the scope sees a 'true' consent value and thus excludes the thesis.
* https://mitlibraries.atlassian.net/browse/ETD-603
This inverts the logic of the not_consented_to_proquest scope. Instead of excluding theses with at least one ProQuest consent value of true, it includes theses with at least one ProQuest consent value of false or nil, using the 'or' method to return the union.
Since 'includes' is not …

Broaden set of theses returned by not_consented_to_proquest scope

---

test/fixtures/authors.yml
test/fixtures/theses.yml
test/integration/thesis_test.rb
test/models/thesis_test.rb

Tests for the `consented_to_proquest` and `not_consented_to_proquest` scopes alter data in fixtures used for previous assertions rather than using fixtures that specifically meet each test case. This can be brittle, if one were to modify the test without noticing the changes in between assertions.
* https://mitlibraries.atlassian.net/browse/ETD-621
This adds more fixtures to meet each test case of the ProQuest consent scopes.
Updated a couple of tests to pass, including refactoring an advisor test not to attempt to select a specific thesis attached to a specific user. That caused the test to fail in this case, and the new approach seems more resilient.
[our …

Refactor tests for consented_to_proquest scopes

---

Gemfile
Gemfile.lock
app/controllers/registrar_controller.rb
app/controllers/report_controller.rb
app/controllers/thesis_controller.rb
app/controllers/transfer_controller.rb
app/models/report.rb
config/environments/development.rb
config/environments/test.rb

* This app has a history of poor performance in production that we have been able to slowly adjust by investigating N+1 queries
* The bullet gem gives us a more structured way of detecting, logging, and addressing these types of issues during development so we can avoid pushing new problems into production
* https://mitlibraries.atlassian.net/browse/ETD-569
* https://mitlibraries.atlassian.net/browse/ETD-570
* https://mitlibraries.atlassian.net/browse/ETD-609
* https://mitlibraries.atlassian.net/browse/ETD-608
* Adds Bullet gem and associated configuration
* Using application in development and test envs, used the information provided to address N+1 queries and removed a few over eager loads. …

Detect N+1 errors in development

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/paper_trail.rb
db/migrate/20230307141544_convert_version_columns_to_json.rb
db/schema.rb
test/integration/admin/admin_hold_test.rb

The versions table, used by paper_trail, has two columns that use
YAML. PaperTrail prefers that these tables use JSON or JSONB.
In order to update paper_trail to the latest version, we need
either to update our config to use YAML.safe_load or migrate
the data to JSON.
* https://mitlibraries.atlassian.net/browse/ETD-626
* https://mitlibraries.atlassian.net/browse/ETD-615
This converts the columns to JSON as described here:
https://github.com/paper-trail-gem/paper_trail/blob/v14.0.0/README.md#6b-custom-serializer
Our migration uses `PaperTrail::Serializers::YAML.load`. This is
effectively the same as `YAML.safe_load`. `YAML.load`,
awhich is uggested in the readme, will no longer work due to a
long-running bug in Psych:
https://github.com/collectiveidea/audited/issues/631
We are using JSON …

Migrate versions.object and versions.object_changes to JSON

---

app/helpers/hold_helper.rb
app/models/hold.rb
test/integration/hold_test.rb
test/models/hold_test.rb

Following the YAML to JSON migration of the versions table, hold statuses render in the UI as integers rather than strings. This is because they were always incorrectly stored as integers, but the PT YAML serializer apparently mapped them to strings as part of the deserialization process.
In JSON, this mapping no longer occurs, so we need some additional data handling to clean up the UI.
* https://mitlibraries.atlassian.net/browse/ETD-629
* https://mitlibraries.atlassian.net/browse/ETD-630
This addresses the two affected parts of the UI:
1. The hold history view, which renders `object_changes` changesets, currently displays integers for hold status. A new hold helper method maps the integers to the correct strings in the UI.
2. The hold admin UI has a 'date released' column that shows …

Render hold status enums correctly

---

config/application.rb

We had temporarily permitted certain data types for YAML unsafe load to support the migration of PaperTrail data in the `versions` table from YAML to JSON. That migration is complete, meaning we no longer use YAML in ETD and this config is no longer needed.
https://mitlibraries.atlassian.net/browse/ETD-628
This removes the unneeded config.
None.
NO
NO

Remove YAML permitted columns config

---

app/views/receipt_mailer/receipt_email.html.erb
app/views/thesis/confirm.html.erb

Part of some recently added text should be emphasized.
https://mitlibraries.atlassian.net/browse/ETD-632
This adds a strong tag around the text to be emphasized.
None.
NO
NO

Add emphasis to thesis confirmation page.

---

app/models/copyright.rb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
test/fixtures/copyrights.yml
test/models/copyright_test.rb

Note: suggested validation steps:
- In the review app, use the author interface to create a new thesis but do not hit submit yet. Note the Copyright options.
- In the administrate panel for Copyright, change a Copyright to display or not so it is different than what you noted in the author display for new.
- Reload the author new form, and note the change has taken place.
- If you save the new thesis, you can then go to the edit view as an author and note the same Copyright display patterns of only showing the correct options in the dropdown.
* We have had a field labeled `display_to_author` in our data model for a long time, but it didn't do anything
* https://mitlibraries.atlassian.net/browse/ETD-633
How does this address that …

Copyright display to author filter

---

app/models/concerns/fake_auth_config.rb
test/models/fake_auth_test.rb

We have a temporary staging app, `thesis-submit-staging-new`, that we will use to test the new S3 bucket and SQS queues in the AWS org. It doesn't make sense to set up this second staging app with Touchstone, so it's best to use fake auth for testing purposes.
N/A.
This allows the new staging app to use fake auth.
We'll want to remove this feature once we're done testing. An inline comment reiterates this. Longer term, it may make sense to log an exception and crash the application if fake auth is attempted in prod. (This is the situation that the `app_name_pattern_match?` method is trying to prevent.)
issues (link to those issues in the Pull …

Enable fake auth for new staging app

---

app/controllers/admin/archivematica_accessions_controller.rb
app/models/thesis.rb
app/views/thesis/process_theses.html.erb
test/fixtures/archivematica_accessions.yml
test/fixtures/degree_periods.yml
test/integration/admin/admin_archivematica_accession_test.rb
test/models/thesis_test.rb

Because we want the accession number to be used in the preservation workflow, we do not want a thesis without an accession number to be published.
https://mitlibraries.atlassian.net/browse/ETD-596
This adds an `accession_number` convenience method to the Thesis model that can look up an accession based on a thesis' degree period. This method is included in the publication checks.
The thesis processing form now shows whether it can find an accession number. If no accession number exists, the form will render a hint that prompts the user to create an accession number for the given degree period.
* A future state of this application is for the Thesis model to belong to the Degree Period model. For now, there is no direct assocation, so we are using ActiveRecord lookups based on the thesis' …

Ensure theses are not publishable without an accession number

---

app/models/submission_information_package.rb
app/models/submission_information_package_zipper.rb
test/models/submission_information_package_test.rb
test/models/submission_information_package_zipper_test.rb

Artefactual has requested that our AWS keys for SIPs should include an Archivematica accession number. This will allow them to automate processing of thesis SIPs.
* https://mitlibraries.atlassian.net/browse/ETD-593
This builds on previous work to rename the AWS key for a given thesis' SIP using the accession number for that thesis.
This will only affect theses preserved _after_ this change is deployed in production. We do not have a plan to retroactively change AWS keys, and stakeholders understand and have agreed to this.
NO
NO

Use Archivematica accession numbers in SIP AWS keys

---

app/models/baggable.rb
app/models/submission_information_package.rb
app/models/thesis.rb
app/views/thesis/process_theses.html.erb
test/models/thesis_test.rb

* we cannot send theses to preservation with duplicate filenames
* preservation is a step after publication, so doing this check before publication will ensure we don't publish things we can't preserve
* https://mitlibraries.atlassian.net/browse/ETD-648
* Moves the baggable? logic to it's own module
* Inlcudes that module in both SIP and Thesis models
* Uses the unique_filenames? check as part of the thesis publication checks
* Adds a visual display to the processor checklist to indicate if filenames are unique
* There is no direct mechanism in the application to allow a processor to resolve duplicate filename issues
[our …

Theses not publishable with duplicate filenames

---

app/views/report_mailer/publication_results_email.html.erb
test/mailers/report_mailer_test.rb

The publication results email lists theses that were "sent to preservation." This language is inaccurate; the theses are queued for preservation at this point, and may not be sent to the Archivematica bucket if the preservation job fails.
https://mitlibraries.atlassian.net/browse/ETD-645
This changes the language to "Total theses queued for preservation."
This does nothing to confirm or report on which theses were actually sent to preservation. (ETD-646 will evaluate the best way to do this.)
NO
NO

Adjust language in publication results email

---

Gemfile
Gemfile.lock

We ran into an issue in prod where we keep getting no message in queue. This is to confirm if the version change caused that.
I believe this is the last version that was used successfully to read from an SQS queue in prod (but I'm not 100% sure of that)
NO
YES

Rollback SQS gem to 1.62.0

---

Gemfile
Gemfile.lock

- the gems have changed an internal protocol that is breaking some tests. We need to rollback to a known working version to resolve production issues and then get to a point where we can upgrade all AWS gems to the latest version.
https://mitlibraries.atlassian.net/browse/ENGX-276
NO
YES

Rollback AWS gems

---

README.md

https://mitlibraries.atlassian.net/browse/ETD-598
Docs only changes.
NO
NO

update publishing to use permormance-m dynos

---

README.md

The readme indicates that the last email to look for while running the publication workflow is the preservation email. The past few times I've run the job, it's been the MARC export email.
N/A
This generalizes the aforementioned note to check for the presence of all three emails, before suggesting that the MARC email may be the last one in the series.
None.
NO
NO

Update note about confirmation emails in publishing workflow docs

---

app/assets/javascripts/student_thesis_form.js
app/models/thesis.rb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

Stakeholders have requested that we preselect the 'author' copyright value, and make the license field conditionally required when that copyright value is selected.
* [ETD-627](https://mitlibraries.atlassian.net/browse/ETD-627)
This adds the `selected` property to the desired option in the copyright field. It also updates the `conditionalLicenseField` function to toggle the `required` property on the license field when it is shown or hidden.
* Past experience has made me wary of toggling the `required` prop in this way. However, it is generally reliable under a single binary condition (either the 'Author' copyright value is selected, or it isn't). I haven't noticed any issues in click-testing.
* `selected` is tied to a value, so in this case we are preselecting the first option. This …

Make requested changes to the copyright and license fields

---

app/views/receipt_mailer/receipt_email.html.erb
test/mailers/receipt_mailer_test.rb

We removed the ProQuest consent field from the thesis submission form, but forgot to remove the field from the mailer. Thus, when a grad student submits their thesis, they see this nonexistent field in their confirmation email.
N/A
This removes the field from the mailer.
None.
NO
NO

Remove ProQuest consent field from receipt email

---

.rubocop.yml
app/models/transfer.rb
config/application.rb

One way to see this change:
* Locally, create a new transfer with a few files
* In a rails console
* `t = Transfer.last`
* `t.files_count`
* `t.unassigned_files_count`
If everything is working as expected, both file counts should match the number of files you attached in the UI. 
To see that this was fixed, revert line 98 in `app/models/transfer.rb` to `save`, restart your server and console and run the same test. You should get 0 `unassigned_files_count` which is incorrect.
https://mitlibraries.atlassian.net/browse/ETD-66
NO
NO

Rails 7.1 framework defaults
