.github/PULL_REQUEST_TEMPLATE.md
.travis.yml

Why:
* :rainbow:
Also adds travis config

Adds a pull request template

---

app/models/advisor.rb
app/models/degree.rb
app/models/department.rb
app/models/right.rb
app/models/thesis.rb
app/models/user.rb
db/migrate/20170713120054_create_theses.rb
db/migrate/20170713120759_add_thesis_to_user.rb
db/migrate/20170713120936_create_departments.rb
db/migrate/20170713121125_join_theses_to_departments.rb
db/migrate/20170713122432_create_degrees.rb
db/migrate/20170713122641_join_theses_to_degrees.rb
db/migrate/20170713123212_create_rights.rb
db/migrate/20170713123352_add_rights_to_theses.rb
db/migrate/20170713123735_create_advisors.rb
db/migrate/20170713123901_add_advisors_to_theses.rb
db/schema.rb
test/fixtures/advisors.yml
test/fixtures/degrees.yml
test/fixtures/departments.yml
test/fixtures/rights.yml
test/fixtures/theses.yml
test/models/advisor_test.rb
test/models/degree_test.rb
test/models/department_test.rb
test/models/right_test.rb
test/models/thesis_test.rb

READY
Adds the models in #4, #5, #6, #7, #8 
`rails db:migrate`, `rails console`, enjoy the presence of these models
- 
YES
NO

Add models

---

Gemfile
Gemfile.lock
app/dashboards/advisor_dashboard.rb
app/dashboards/degree_dashboard.rb
app/dashboards/department_dashboard.rb
app/dashboards/right_dashboard.rb
app/dashboards/thesis_dashboard.rb
app/dashboards/user_dashboard.rb
test/models/thesis_test.rb

**READY**
Addresses some linter concerns as prep for enabling CodeClimate.
NO
YES -- adds rubocop to the bundle to ensure the same version is available to all developers when run via `bundle exec rubocop`

rubocop cleanup

---

README.md

**READY**
adds travis, codeclimate and gemnasium badges
YES
YES

adds travis, codeclimate and gemnasium badges

---

Gemfile
Gemfile.lock
app/controllers/thesis_controller.rb
app/models/thesis.rb
app/views/thesis/new.html.erb
config/initializers/simple_form.rb
config/locales/simple_form.en.yml
config/routes.rb
lib/templates/erb/scaffold/_form.html.erb
test/controllers/thesis_controller_test.rb
test/models/thesis_test.rb
test/test_helper.rb

**READY**
Creates the initial user facing Thesis submission form.
Advisor validation is temporarily removed from the Thesis model to allow web form work to
proceed with the simpler elements before tackling this more complex form element. A new ticket #22  will handle Advisors in the web form and the validation and tests will be reenabled at that time.
- `bundle install` to get the new dependencies
- Locally, run the application with `heroku local` 
- access `/thesis/new`
- see the new (missing advisors and file uploads still) web form
- #19 
NO
YES

18 initial thesis submission form

---

.adr-dir
Gemfile
Gemfile.lock
Procfile
README.md
app/controllers/application_controller.rb
app/controllers/thesis_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/views/layouts/_site_header.html.erb
config/environments/test.rb
config/initializers/devise.rb
docs/architecture_decisions/0001-record-architecture-decisions.md
docs/architecture_decisions/0002-authentication-via-touchstone-saml.md
docs/architecture_decisions/0003-deploy-via-heroku-pipelines.md
test/fixtures/files/testshib-providers.xml
test/integration/admin_dashboard_test.rb
test/integration/authentication_test.rb
test/test_helper.rb

**READY**
- changes auth from MIT Pilot to MIT Touchstone via in app SAML SP
- provides a dev mode auth option for PR builds and local work as
registering a Touchstone SP for each PR and local environment is
tedious
- also adds db migrate to release phase
https://mitlibraries.github.io/touchstone_saml.html
Login at https://library-thesis-dropbox-staging.mit.edu
YES
YES

Touchstone SAML

---

app/controllers/thesis_controller.rb
app/views/thesis/show.html.erb
test/controllers/thesis_controller_test.rb
test/fixtures/degrees.yml

**READY**
Redirects to thesis_path after successful submission, showing users that we got their thesis metadata (along with displaying the 'yay it worked' flash message).
Submit something valid on the PR build. Woot!
- https://mitlibraries.atlassian.net/browse/TI-27
NO
NO

27 receipt screen

---

Gemfile
Gemfile.lock
app/controllers/thesis_controller.rb
app/models/ability.rb
config/routes.rb
test/controllers/thesis_controller_test.rb
test/fixtures/users.yml

**READY**
Adds initial roles and tests to confirm expectations.
https://github.com/CanCanCommunity/cancancan
The PR builds are broken (ticket is open) but if you look at this locally you can create a couple users and give one a thesis and confirm the other can't see it.
- https://mitlibraries.atlassian.net/browse/TI-6
NO
YES

Adds initial roles

---

app.json
app/models/concerns/fake_auth_config.rb
test/models/fake_auth_test.rb

**READY**
Apparently valid JSON is a good thing.
If the PR build works, it work!
- https://mitlibraries.atlassian.net/browse/TI-36
NO
NO

valid json ftw

---

app/views/static/index.html.erb

**READY**
Adds text to the splash page.
This is the current text of our submission system, as supplied by Mikki, except without the part about filesize limits since that may not apply in our case. It will probably change after testing. There aren't any tests because I am not in the business of testing web page text unless there's a really good reason to - those tests are too brittle.
Look at `'/'` while not logged in. It does not say "Hi!" any more.
- https://mitlibraries.atlassian.net/browse/TI-25
NO
NO

Add text of splash page

---

Gemfile
Gemfile.lock
app/controllers/thesis_controller.rb
app/models/ability.rb
app/views/layouts/_site_header.html.erb
app/views/thesis/process_theses.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb

**READY**
Adds a thesis processing queue page.
Log into PR build as admin, go to /process (or just click the link that will be visible in the nav post-login)
- https://mitlibraries.atlassian.net/browse/TI-35
NO
YES

35 admin page

---

app/controllers/thesis_controller.rb
app/views/thesis/process_theses.html.erb
test/controllers/thesis_controller_test.rb

* Make sure the view HTML buttons are consistent with the new URLs
* Change queryset in controller
* Update tests to reflect new desired behavior
* Also update tests to use named URLs because they're better
**READY**
(see above)
Compare `/process` on the PR build and the staging build (first making sure that there are both active and non-active theses available).
- https://mitlibraries.atlassian.net/browse/TI-49
NO
NO

Restrict main processing queue to active theses only

---

app/assets/stylesheets/thing.scss

**READY**
Overrides header and footer wrapper classes to use asset pipeline
versions of svg.
NO
NO

Overrides header and footer wrapper

---

app/controllers/thesis_controller.rb
app/dashboards/user_dashboard.rb
app/helpers/thesis_helper.rb
app/models/thesis.rb
app/models/user.rb
app/views/thesis/process_theses.html.erb
test/controllers/thesis_controller_test.rb

**READY**
Allows thesis processors to sort the queue by name.
- https://mitlibraries.atlassian.net/browse/TI-39
NO
NO

39 sort options

---

app/controllers/thesis_controller.rb
app/helpers/thesis_helper.rb
app/models/thesis.rb
app/views/thesis/_empty.html.erb
app/views/thesis/_thesis.html.erb
app/views/thesis/process_theses.html.erb
test/controllers/thesis_controller_test.rb
test/fixtures/theses.yml

**READY**
Includes:
* Date filtering form added to HTML
* process_theses actions for validating dates and filtering Theses
accordingly
* Helpers to ensure that the thesis date range is not stupid, and the
date filtering form is only shown when there are things to filter
* Test coverage
- https://mitlibraries.atlassian.net/browse/TI-62
NO
NO

Add filter-by-date functionality

---

app/views/thesis/new.html.erb

**READY**
- adds label to file input
- adds hint to file input
- adds list of files to be uploaded once selected
Upload a file in the PR build
- https://mitlibraries.atlassian.net/browse/TI-73
NO
NO

displays list of files selected for upload and adds hint

---

app/views/static/index.html.erb

**READY**
Makes the homepage more readable/scannable.
- https://mitlibraries.atlassian.net/browse/TI-75
- https://mitlibraries.atlassian.net/browse/TI-78

adjust homepage layout and copy

---

README.md

**READY**
- removes gemnasium badge
- adds depfu badge
It's just a link in the readme. No code changes.
NO
NO

Add depfu badge

---

app/views/static/index.html.erb

**READY**
Adds working get started links to splash page
- https://mitlibraries.atlassian.net/browse/TI-86
NO
NO

Adds working get started links to splash page

---

app/views/thesis/new.html.erb

**READY**
Adds a sidebar with form tips to the form page.
- https://mitlibraries.atlassian.net/browse/TI-76

add sidebar to form page

---

app/assets/stylesheets/thing.scss
app/models/thesis.rb
app/views/layouts/_head.html.erb
app/views/thesis/new.html.erb

**READY**
Adds client side form validation and hints.
Look at the form.
- https://mitlibraries.atlassian.net/browse/TI-82
NO
YES -- sort of, pulling in a CDN version of jQuery Validate so no need to bundle but technically a new external dependency is being added

Initial hints and errors

---

app/assets/stylesheets/libraries-global.scss
app/assets/stylesheets/thing.scss
app/views/thesis/_thesis.html.erb
app/views/thesis/show.html.erb

Make the processing panels more semantic

---

app/models/user.rb
app/views/thesis/new.html.erb
test/integration/thesis_test.rb

**READY**
Indicate in the thesis submission context that we know who the current user is, to reassure them we'll process their submission correctly.
- https://mitlibraries.atlassian.net/browse/TI-88
NO
NO

88 indicate active user

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/libraries-global.scss
app/views/layouts/_site_header.html.erb
app/views/static/index.html.erb
app/views/thesis/new.html.erb
app/views/thesis/process_theses.html.erb
app/views/thesis/show.html.erb

**READY**
Adds the newest of the new branding styling for content areas.

Update global css and variables with new branding

---

app/assets/stylesheets/libraries-global.scss
app/assets/stylesheets/thing.scss
app/views/thesis/_inner_stats.html.erb

**READY**
Brings in table stying from the style guide - removes local table style rules (as seen on stats page).

Add table styling

---

app/models/thesis.rb
app/views/thesis/new.html.erb

**READY**
A few small fixes to the form experience for screenreaders.

a11y adjustments

---

app/helpers/link_helper.rb
app/views/layouts/_site_header.html.erb
test/integration/nav_test.rb

**READY/**
add screen reader span  and visual class for nav elements
Click through nav on pr app. Note you can tell which page you are on in the nav. Inspect elements to see the sr span.
- https://mitlibraries.atlassian.net/browse/TI-93
NO
NO

add screen reader and visual class for nav elements

---

app/views/thesis/new.html.erb

**READY**
Adds banner when client side form validation fails.
- https://mitlibraries.atlassian.net/browse/TI-94
NO
NO

Display accessible error banner on validation fail

---

app/views/static/index.html.erb
app/views/thesis/new.html.erb
app/views/thesis/show.html.erb

**READY**
Small text changes requested by stakeholders.
- https://mitlibraries.atlassian.net/browse/TI-99
- https://mitlibraries.atlassian.net/browse/TI-100
- https://mitlibraries.atlassian.net/browse/TI-95
- https://mitlibraries.atlassian.net/browse/TI-98
NO
NO

Text changes

---

app/assets/stylesheets/libraries-global.scss
app/assets/stylesheets/thing.scss
app/views/thesis/new.html.erb

**READY**
Makes inline form fields align better.
- https://mitlibraries.atlassian.net/browse/TI-107

updated style guide with aligned inline form fields

---

app/views/thesis/_thesis.html.erb

**READY**
Processors requested we include date and time display on the processing page.
- https://mitlibraries.atlassian.net/browse/TI-103
NO
NO

Adds submission date and time

---

.rubocop.yml
README.md
config/storage.yml

**READY**
We had a fix in place for a RC build that was fixed in final and this removes that fix as our fix was actually breaking things now that it was fixed.
- https://mitlibraries.atlassian.net/browse/TI-108
NO
NO

Removes activestorage config causing issues after 5.2 final

---

app/views/thesis/new.html.erb

**READY**
Uses aria-desribedby for html selects with hints
inspect appropriate form elements in PR build
https://mitlibraries.atlassian.net/browse/TI-112
https://github.mit.edu/Accessibility-FY2018/thesis-submission/issues/2
NO
NO

Use aria-desribedby for html selects with hints

---

README.md

**READY**
Updates documentation to explain what the roles are and note who can
assign them.
NO
NO

Document various Roles

---

.github/workflows/ci.yml
.travis.yml
Gemfile
Gemfile.lock
README.md
test/test_helper.rb

**READY**
Moves our continuous integration from Travis CI to GitHub Actions.
We are now using GitHub Actions for CI and updating existing projects accordingly.
The action should pass in this PR.
- https://mitlibraries.atlassian.net/secure/RapidBoard.jspa?rapidView=127&view=planning&selectedIssue=ENGX-2&issueLimit=100
NO
YES

Change CI from Travis to GitHub Actions

---

app/controllers/thesis_controller.rb
app/views/receipt_mailer/receipt_email.html.erb
app/views/static/index.html.erb
app/views/thesis/new.html.erb
test/fixtures/receipt_mailer/receipt_email

**READY**
Updates wording in various places to handle the May 2020 degree period.
These are generally wording updates the stakeholders will confirm are as they expected. Code review to ensure I didn't do anything dumb would be 🌈 
- https://mitlibraries.atlassian.net/browse/TI-132
- https://mitlibraries.atlassian.net/browse/TI-133
- https://mitlibraries.atlassian.net/browse/TI-134
NO
NO

Ti 132 submission form update

---

app/models/concerns/fake_auth_config.rb
test/models/fake_auth_test.rb

**READY**
updates or sanity check for fake auth to use new pr build naming parameters for the updated pipelines
NO
YES

updates to use new heroku pr build naming pattern

---

README.md

* The application is currently undergoing major feature development
* We need a way to maintain the production application without making
work on the new features more complicated
* This documents the new `1.x` branch that has been created with notes
on how to update production during this feature development period.
Someone will need to remember to delete this note when it no longer
makes sense.
NO
NO

Document current production branch plan

---

app/controllers/admin/submitters_controller.rb
app/controllers/transfer_controller.rb
app/dashboards/submitter_dashboard.rb
app/models/transfer.rb
app/models/user.rb
app/views/layouts/_site_nav.html.erb
app/views/transfer/new.html.erb
config/routes.rb
test/integration/transfer_test.rb
test/models/user_test.rb

** Relevant ticket(s):
* https://mitlibraries.atlassian.net/browse/ETS-33
NO
NO

ETS-33 Adds a basic UI for Transfers, including integration tests

---

app/views/receipt_mailer/receipt_email.html.erb
app/views/static/index.html.erb
app/views/thesis/new.html.erb
test/fixtures/receipt_mailer/receipt_email

This updates our references to recent terms to include "February 2021" - in some cases replacing "May or September 2020", and in some cases adding it to the list. A bit more details are in the commit message.
NO
NO

Updates mentions of terms for February 2021

---

app/models/hold.rb
app/models/hold_source.rb
app/models/thesis.rb
db/migrate/20210111000000_create_holds.rb
db/schema.rb
db/seeds.rb
test/fixtures/hold_sources.yml
test/fixtures/holds.yml
test/fixtures/theses.yml
test/helpers/thesis_helper_test.rb
test/models/hold_source_test.rb
test/models/hold_test.rb
test/models/thesis_test.rb

This is a re-submission of the PR in #583 - which I merged too early (and have since reverted with #584).
This PR is meant for review by @hakbailey as the data model stakeholder.
YES
NO

REDO: Adds models for holds and hold_sources

---

app/controllers/admin/hold_sources_controller.rb
app/controllers/admin/holds_controller.rb
app/dashboards/hold_dashboard.rb
app/dashboards/hold_source_dashboard.rb
app/dashboards/thesis_dashboard.rb
app/models/hold_source.rb
config/routes.rb
test/integration/admin_dashboard_test.rb

Create a basic UI for managing Hold records

---

app/controllers/admin/department_theses_controller.rb
app/dashboards/department_thesis_dashboard.rb
app/models/department_thesis.rb
config/routes.rb
db/migrate/20210128183652_add_primary_to_department_thesis.rb
db/schema.rb
test/fixtures/department_theses.yml
test/fixtures/theses.yml
test/helpers/thesis_helper_test.rb
test/integration/admin_dashboard_test.rb
test/models/department_thesis_test.rb

This adds the Primary flag to the Department_Thesis table. There are some associated changes with this ticket which are described in the commit message. I'd rather not type them all out here again, but will copy-paste if reviewers want.
Ticket: https://mitlibraries.atlassian.net/browse/ETD-64
YES
NO

Adds Primary field to Department-Thesis relationship

---

app/models/ability.rb
app/models/user.rb
app/views/layouts/_site_nav.html.erb
test/models/user_test.rb

Convert transfer_submitter role to implicitly-defined

---

app/controllers/registrar_controller.rb
app/jobs/registrar_import_job.rb
app/views/registrar/_empty_job.html.erb
app/views/registrar/_empty_registrar.html.erb
app/views/registrar/_job.html.erb
app/views/registrar/_registrar.html.erb
app/views/registrar/list_registrar.html.erb
app/views/registrar/process_registrar.html.erb
config/routes.rb
test/controllers/registrar_controller_test.rb
test/jobs/registrar_import_job_test.rb

This implements the basic framework around an asynchronous worker that will handle the data import for records in the Registrar CSV file.
NO
NO

Speculative implementation of Registrar CSV processing

---

test/integration/admin_dashboard_test.rb

We want to confirm both that a hold can be moved to another thesis and
that the audit updates accordingly when such a move is made.
* https://mitlibraries.atlassian.net/browse/ETD-152
Moving holds is already tested in the Thesis model spec. This PR adds
testing that confirms the audit trail piece.
* The ticket mentions that thesis processors should be able to do this in
the UI, but thesis processors can't access the admin dashboards at all.
I've created a ticket for that here: https://mitlibraries.atlassian.net/browse/ETD-190
* We currently move holds to a new thesis based on the thesis title.
Pending stakeholder feedback, we may want to change that.
all issues introduced by these changes …

ETD-152 Confirm audit trail updates when moving a hold to another thesis

---

app/dashboards/department_dashboard.rb
app/models/department.rb
app/models/registrar.rb
app/models/user.rb
app/views/thesis/_thesis.html.erb
app/views/thesis/new.html.erb
app/views/thesis/show.html.erb
app/views/transfer/new.html.erb
db/migrate/20210304142225_add_data_to_departments.rb
db/schema.rb
db/seeds.rb
test/controllers/thesis_controller_test.rb
test/fixtures/departments.yml
test/fixtures/users.yml
test/integration/admin_dashboard_test.rb
test/models/author_test.rb
test/models/department_test.rb
test/models/registrar_test.rb
test/models/user_test.rb

Update department model

---

Gemfile.lock

This is just an update to the Mimemagic gem, which yanked all previous releases earlier this morning and then published a new one after quick feedback.
NO
YES

Updates Mimemagic to 0.3.6

---

app/assets/stylesheets/thing.scss
app/controllers/thesis_controller.rb
app/views/thesis/_advisor_fields.html.erb
app/views/thesis/_sidebar.html.erb
app/views/thesis/_welcome.html.erb
app/views/thesis/confirm.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
app/views/thesis/start.html.erb

Updates student submission UI based on feedback

---

app/jobs/registrar_import_job.rb

An error in production identified a few places in the registrar
import where more detailed logging would be helpful.
* Adds detailed logging to the registrar import job.
More logs.
* https://mitlibraries.atlassian.net/browse/ETD-226
NO
NO

Add more logging to registrar import

---

app/assets/stylesheets/thing.scss
app/models/thesis.rb
app/views/static/index.html.erb
app/views/thesis/_advisor_fields.html.erb
app/views/thesis/_sidebar.html.erb
app/views/thesis/_welcome.html.erb
app/views/thesis/confirm.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb

This implements a variety of wording changes around the interface, in response to feedback received during user testing.
Ticket: https://mitlibraries.atlassian.net/browse/ETD-238
NO
NO

Wording changes based on user testing

---

app/views/receipt_mailer/receipt_email.html.erb
test/fixtures/receipt_mailer/receipt_email

More stakeholder feedback came in about the confirmation email.
* https://mitlibraries.atlassian.net/browse/ETD-200
This reformats the email further.
None.
NO
NO

Additional reformatting to student submission confirmation email

---

app/views/receipt_mailer/transfer_receipt_email.html.erb

This implements some requested changes to the transfer receipt email that have been requested by Stephanie. This is an outgrowth of #691 .
Ticket: https://mitlibraries.atlassian.net/browse/ETD-79
NO
NO

QA-induced changes to transfer receipt email

---

app/views/thesis/_advisor_fields.html.erb
app/views/transfer/_welcome.html.erb

This makes a few UI adjustments based on testing and QA feedback.
* https://mitlibraries.atlassian.net/browse/ETD-286
* https://mitlibraries.atlassian.net/browse/ETD-283
NO
NO

Updates to Transfer and Thesis forms

---

app/assets/javascripts/direct_uploads.js
app/assets/stylesheets/direct_uploads.scss
app/views/transfer/_welcome.html.erb

** Why are these changes being introduced:
* Some text elements on the new transfer form need to be slightly
clearer. This includes the live status panel that reports status of
the file upload process.
** Relevant ticket(s):
* https://mitlibraries.atlassian.net/browse/ETD-290
** How does this address that need:
* This updates the wording in the welcome panel, and the live update
panel, for the new transfer form. The wording used comes from the
Axure mockup provided by Stephanie.
** Document any side effects to this change:
* None
NO
NO

Updates wording on new transfer form

---

app/assets/javascripts/student_thesis_form.js
app/assets/stylesheets/thing.scss
app/controllers/thesis_controller.rb
app/models/ability.rb
app/models/thesis.rb
app/views/thesis/_department_thesis_fields.html.erb
app/views/thesis/_select_thesis.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
app/views/thesis/process_theses.html.erb
app/views/transfer/show.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb
test/fixtures/authors.yml
test/fixtures/holds.yml
test/fixtures/theses.yml
test/models/hold_source_test.rb
test/models/thesis_test.rb

Details in the commit message. More verbose history in the ticket:
https://mitlibraries.atlassian.net/browse/ETD-309
The follow-up ticket for the publication status field is https://mitlibraries.atlassian.net/browse/ETD-343
NO
NO

Implements thesis processing form

---

app/dashboards/submitter_dashboard.rb

This enables staff searching of records within the admin submitter panel.
- https://mitlibraries.atlassian.net/browse/ETD-316
NO
NO

Adds searchable flag to certain submitter fields

---

README.md

Remove typo in README, one 'to' is sufficient

---

app/views/thesis/_sidebar.html.erb
app/views/thesis/edit.html.erb
app/views/thesis/new.html.erb
app/views/thesis/process_theses.html.erb

Stakeholders have requested some wording changes in the student
submission form.
https://mitlibraries.atlassian.net/browse/ETD-390
This makes the requested changes.
None.
NO
NO

Update links in student submission page

---

app/views/thesis/process_theses.html.erb

Stakeholders requested these changes after using the application
for processing.
* https://mitlibraries.atlassian.net/browse/ETD-384
* https://mitlibraries.atlassian.net/browse/ETD-385
This adds two requested changes:
* Move the form submit button to the 'Status of all the things' div.
* Open the admin interface link in the degree date field in a new tab.
None.
NO
NO

ETD-384 ETD-385 Updates to the thesis processing UI

---

app/views/transfer/_welcome.html.erb

There are time-specific (and dated) references in the welcoming text atop the transfer form. This text should be updated to be current, and ideally less time-sensitive.
* https://mitlibraries.atlassian.net/browse/etd-439
This updates the welcome text along the lines of the Google doc linked in the Jira ticket above.
This new template actually conforms to the 120 character line length limit that we've recently adopted.
NO
NO

Updates welcome text atop the transfer form

---

app/controllers/thesis_controller.rb
app/models/ability.rb
app/views/thesis/publish_preview.html.erb
app/views/thesis/select.html.erb
config/routes.rb
test/controllers/thesis_controller_test.rb

Details in the commit message, and the updated workflow is in the Jira ticket with screenshots. I'd recommend reviewing that as part of code review.
I'm waiting on stakeholder input in the Jira ticket as well, but the code review can probably happen in parallel if desired.
https://mitlibraries.atlassian.net/browse/ETD-477
NO
NO

Unifies logic to assemble cohort of to-be-published theses

---

Gemfile.lock

Doing this manually because there is a bug in v1.4.3, and depfu hasn't yet picked up on the latest release.
NO
YES

Update sqlite3 to v1.4.4

---

README.md

The ProQuest export workflow is fairly complex and should be documented.
* https://mitlibraries.atlassian.net/browse/ETD-622
This adds information about the export workflow to the readme.
None.
NO
NO

Document ProQuest export workflow

---

app/views/receipt_mailer/receipt_email.html.erb
app/views/thesis/confirm.html.erb

After reviewing the recently requested changes, stakeholders have asked that we add information about submitting files.
https://mitlibraries.atlassian.net/browse/ETD-632
This adds the requested bullet point.
None.
NO
NO

Further changes to the thesis receipt confirmation language

---

README.md

We need to scale up the dyno for the publication post-processing job. This is not currently documented.
https://mitlibraries.atlassian.net/browse/ETD-650
This adds a note about dyno scaling to the publishing workflow section of the readme.
None.
NO
NO

Add note about dyno scaling in pub workflow to readme
